Loading_bis_table = {
{["loot_id"] = "30888", ["loot_name"] = "Anetheron's Noose", ["prio"] = "Magicbulb, Cornholio, Frostafarion",},
{["loot_id"] = "30895", ["loot_name"] = "Angelista's Sash", ["prio"] = "Kronkey",},
{["loot_id"] = "30909", ["loot_name"] = "Antonidas's Aegis of Rapt Concentration", ["prio"] = "Enkai, Schizm",},
{["loot_id"] = "29949", ["loot_name"] = "arcanite steam-pistol", ["prio"] = "Belialx",},
{["loot_id"] = "32486", ["loot_name"] = "Ashtongue Talisman of Equilibrium", ["prio"] = "Jest",},
{["loot_id"] = "29172", ["loot_name"] = "Ashyen's Gift", ["prio"] = "Cheeps",},
{["loot_id"] = "32526", ["loot_name"] = "Band of Devastation", ["prio"] = "Daemir",},
{["loot_id"] = "29301", ["loot_name"] = "band of the eternal champion", ["prio"] = "Kravens, Momochi, Belialx, Mitsaff",},
{["loot_id"] = "29297", ["loot_name"] = "band of the eternal defender", ["prio"] = "Cheeps",},
{["loot_id"] = "29309", ["loot_name"] = "band of the eternal restorer", ["prio"] = "Amoxichillin, Cheattis",},
{["loot_id"] = "29305", ["loot_name"] = "band of the eternal sage", ["prio"] = "Guldan, Magicbulb, Sygdot, Schizm, Frostafarion, Norpse",},
{["loot_id"] = "30882", ["loot_name"] = "Bastion of Light", ["prio"] = "Hashmeer, Saasuntwo, Eklm",},
{["loot_id"] = "30038", ["loot_name"] = "Belt of blasting", ["prio"] = "Jest, Guldan, Sygdot",},
{["loot_id"] = "30106", ["loot_name"] = "Belt of One-Hundred Deaths", ["prio"] = "Roidsrage, Jiffypop, Belialx, Daemir, Verystrong",},
{["loot_id"] = "32339", ["loot_name"] = "belt of primal majesty", ["prio"] = "Amoxichillin",},
{["loot_id"] = "32574", ["loot_name"] = "Bindings of Lightning Reflexes", ["prio"] = "Daemir",},
{["loot_id"] = "32336", ["loot_name"] = "Black bow of the betrayer", ["prio"] = "Kravens",},
{["loot_id"] = "30881", ["loot_name"] = "Blade of Infamy", ["prio"] = "Momochi, Mitsaff, Mitsaff, Kravens",},
{["loot_id"] = "30862", ["loot_name"] = "Blessed Adamantite Bracers", ["prio"] = "Cheattis",},
{["loot_id"] = "32528", ["loot_name"] = "Blessed Band of Karabor", ["prio"] = "Hashmeer, Hashmeer, Kronkey, Kronkey, Amoxichillin, Saasuntwo, Saasuntwo, eklm, eklm",},
{["loot_id"] = "29383", ["loot_name"] = "Bloodlust Brooch", ["prio"] = "Daemir",},
{["loot_id"] = "32346", ["loot_name"] = "Boneweave Girdle", ["prio"] = "Kravens",},
{["loot_id"] = "32609", ["loot_name"] = "Boots of the Divine Light", ["prio"] = "Kronkey, Eklm",},
{["loot_id"] = "32328", ["loot_name"] = "Botanist's Gloves of Growth", ["prio"] = "Hashmeer, Amoxichillin, Saasuntwo, Eklm",},
{["loot_id"] = "30901", ["loot_name"] = "Boundless Agony", ["prio"] = "Momochi, Kravens",},
{["loot_id"] = "30900", ["loot_name"] = "bow-stitched leggings", ["prio"] = "Mitsaff, Daemir",},
{["loot_id"] = "32586", ["loot_name"] = "Bracers of Nimble Thought", ["prio"] = "Jest, Guldan, Enkai, Sygdot, Cornholio, Schizm, Frostafarion, Norpse, Rezthedead",},
{["loot_id"] = "32582", ["loot_name"] = "Bracers of Renewed Life", ["prio"] = "Amoxichillin",},
{["loot_id"] = "30906", ["loot_name"] = "Bristleblitz Striker", ["prio"] = "Momochi, Mitsaff",},
{["loot_id"] = "32375", ["loot_name"] = "Bulwark of Azzinoth", ["prio"] = "Cheeps, Verystrong",},
{["loot_id"] = "31089", ["loot_name"] = "Chestguard of the Forgotten Conqueror", ["prio"] = "Cheeps, Kronkey, Cornholio, Rezthedead, Cheattis",},
{["loot_id"] = "31091", ["loot_name"] = "Chestguard of the Forgotten Protector", ["prio"] = "Momochi, Roidsrage, Enkai, Hashmeer, Mitsaff, Schizm, Kravens, Saasuntwo, Verystrong, Eklm",},
{["loot_id"] = "31090", ["loot_name"] = "Chestguard of the Forgotten Vanquisher", ["prio"] = "Jest, Jiffypop, Belialx, Amoxichillin, Frostafarion",},
{["loot_id"] = "30238", ["loot_name"] = "Chestguard of the Vanquished Hero", ["prio"] = "Magicbulb, Norpse",},
{["loot_id"] = "32260", ["loot_name"] = "Choker of endless nightmares", ["prio"] = "Belialx",},
{["loot_id"] = "32591", ["loot_name"] = "Choker of Serrated blades", ["prio"] = "Momochi, Roidsrage, Kravens",},
{["loot_id"] = "30872", ["loot_name"] = "Chronicle of Dark Secrets", ["prio"] = "Guldan, Norpse",},
{["loot_id"] = "32331", ["loot_name"] = "Cloak of the Illidari Council", ["prio"] = "Guldan, Schizm, Frostafarion",},
{["loot_id"] = "32525", ["loot_name"] = "Cowl of the Illidari High Lord", ["prio"] = "Frostafarion",},
{["loot_id"] = "32500", ["loot_name"] = "Crystal Spire of Karabor", ["prio"] = "Hashmeer, Kronkey, Amoxichillin, Saasuntwo, Cheattis, Eklm",},
{["loot_id"] = "30870", ["loot_name"] = "Cuffs of Devastation", ["prio"] = "Magicbulb",},
{["loot_id"] = "32235", ["loot_name"] = "Cursed Vision of Sargeras", ["prio"] = "Momochi, Roidsrage, Belialx, Daemir, Kravens",},
{["loot_id"] = "31859", ["loot_name"] = "Darkmoon Card: Madness", ["prio"] = "Verystrong",},
{["loot_id"] = "30863", ["loot_name"] = "Deadly Cuffs", ["prio"] = "Roidsrage",},
{["loot_id"] = "30879", ["loot_name"] = "Don Alejandro's Money Belt", ["prio"] = "Momochi, Mitsaff",},
{["loot_id"] = "28830", ["loot_name"] = "Dragonspine Trophy", ["prio"] = "Momochi, Roidsrage, Mitsaff, Daemir, Kravens",},
{["loot_id"] = "32345", ["loot_name"] = "Dreadboots of the Legion", ["prio"] = "Roidsrage",},
{["loot_id"] = "30665", ["loot_name"] = "Earring of Soulful Meditation", ["prio"] = "Kronkey",},
{["loot_id"] = "28783", ["loot_name"] = "Eredar wand of obliteration", ["prio"] = "Norpse",},
{["loot_id"] = "29376", ["loot_name"] = "Essence of the Martyr", ["prio"] = "Hashmeer, Kronkey, Amoxichillin, Amoxichillin, Saasuntwo, Cheattis, Eklm",},
{["loot_id"] = "28789", ["loot_name"] = "eye of Magtheridon", ["prio"] = "Cheeps",},
{["loot_id"] = "32521", ["loot_name"] = "Faceplate of the Impenetrable", ["prio"] = "Cheeps, Verystrong",},
{["loot_id"] = "32255", ["loot_name"] = "Felstone Bulwark", ["prio"] = "Cheattis",},
{["loot_id"] = "32276", ["loot_name"] = "Flashfire Girdle", ["prio"] = "Enkai, Schizm",},
{["loot_id"] = "21870", ["loot_name"] = "frozen shadoweave boots", ["prio"] = "Rezthedead",},
{["loot_id"] = "32280", ["loot_name"] = "Gauntlets of Enforcement", ["prio"] = "Verystrong",},
{["loot_id"] = "28660", ["loot_name"] = "Gilded Thorium Cloak", ["prio"] = "Jiffypop",},
{["loot_id"] = "30897", ["loot_name"] = "Girdle of Hope", ["prio"] = "Cheattis",},
{["loot_id"] = "32342", ["loot_name"] = "Girdle of Mighty Resolve", ["prio"] = "Cheeps",},
{["loot_id"] = "30112", ["loot_name"] = "Glorious gauntlets of crestfall", ["prio"] = "Cheattis",},
{["loot_id"] = "31092", ["loot_name"] = "Gloves of the Forgotten Conqueror", ["prio"] = "Cheeps, Guldan, Kronkey, Sygdot, Cornholio, Rezthedead",},
{["loot_id"] = "31094", ["loot_name"] = "Gloves of the Forgotten Protector", ["prio"] = "Momochi, Enkai, Mitsaff, Schizm, Kravens",},
{["loot_id"] = "31093", ["loot_name"] = "Gloves of the Forgotten Vanquisher", ["prio"] = "Jest, Jiffypop, Belialx, Frostafarion",},
{["loot_id"] = "29947", ["loot_name"] = "Gloves of the Searing Grip", ["prio"] = "Daemir",},
{["loot_id"] = "30241", ["loot_name"] = "Gloves of the Vanquished Hero", ["prio"] = "Magicbulb, Norpse",},
{["loot_id"] = "32278", ["loot_name"] = "Grips of Silent Justice", ["prio"] = "Roidsrage",},
{["loot_id"] = "32589", ["loot_name"] = "Hellfire-Encased Pendant", ["prio"] = "Frostafarion",},
{["loot_id"] = "31097", ["loot_name"] = "Helm of the Forgotten Conqueror", ["prio"] = "Guldan, Kronkey, Sygdot, Cornholio, Rezthedead, Cheattis",},
{["loot_id"] = "31095", ["loot_name"] = "Helm of the Forgotten Protector", ["prio"] = "Enkai, Hashmeer, Mitsaff, Schizm, Saasuntwo, Eklm",},
{["loot_id"] = "31096", ["loot_name"] = "Helm of the Forgotten Vanquisher", ["prio"] = "Jest, Jiffypop, Amoxichillin",},
{["loot_id"] = "30244", ["loot_name"] = "Helm of the Vanquished Hero", ["prio"] = "Magicbulb, Norpse",},
{["loot_id"] = "30869", ["loot_name"] = "Howling Wind Bracers", ["prio"] = "Eklm",},
{["loot_id"] = "29370", ["loot_name"] = "Icon of the silver crescent", ["prio"] = "Cheeps, Guldan, Sygdot, Schizm, Frostafarion, Rezthedead, Rezthedead",},
{["loot_id"] = "27886", ["loot_name"] = "Idol of the emerald queen", ["prio"] = "Amoxichillin",},
{["loot_id"] = "32387", ["loot_name"] = "Idol of the Raven Goddess", ["prio"] = "Jest, Jiffypop",},
{["loot_id"] = "32324", ["loot_name"] = "Insidious Bands", ["prio"] = "Momochi, Belialx, Mitsaff, Kravens",},
{["loot_id"] = "30916", ["loot_name"] = "Leggings of Channeled elements", ["prio"] = "Jest, Enkai, Cornholio, Schizm",},
{["loot_id"] = "32367", ["loot_name"] = "Leggings of devastation", ["prio"] = "Rezthedead",},
{["loot_id"] = "32341", ["loot_name"] = "Leggings of Divine Retribution", ["prio"] = "Roidsrage",},
{["loot_id"] = "30912", ["loot_name"] = "Leggings of Eternity", ["prio"] = "Kronkey, Amoxichillin",},
{["loot_id"] = "31098", ["loot_name"] = "Leggings of the Forgotten Conqueror", ["prio"] = "Cheeps, Guldan, Sygdot, Cheattis",},
{["loot_id"] = "31100", ["loot_name"] = "Leggings of the Forgotten Protector", ["prio"] = "Momochi, Hashmeer, Saasuntwo, Kravens, Verystrong, Eklm",},
{["loot_id"] = "31099", ["loot_name"] = "Leggings of the Forgotten Vanquisher", ["prio"] = "Jiffypop, Belialx, Magicbulb, Frostafarion, Norpse",},
{["loot_id"] = "32253", ["loot_name"] = "Legionkiller", ["prio"] = "Verystrong",},
{["loot_id"] = "27484", ["loot_name"] = "Libram of Avengement", ["prio"] = "Daemir",},
{["loot_id"] = "28296", ["loot_name"] = "Libram of the lightbringer", ["prio"] = "Cheattis",},
{["loot_id"] = "32577", ["loot_name"] = "Living Earth Bindings", ["prio"] = "Hashmeer, Saasuntwo",},
{["loot_id"] = "30018", ["loot_name"] = "Lord Sanguinar's Claim", ["prio"] = "Amoxichillin",},
{["loot_id"] = "32505", ["loot_name"] = "Madness of the Betrayer", ["prio"] = "Momochi, Roidsrage, Jiffypop, Belialx, Mitsaff, Kravens, Verystrong",},
{["loot_id"] = "32496", ["loot_name"] = "Memento of Tyrande", ["prio"] = "Hashmeer, Saasuntwo, Cheattis, eklm",},
{["loot_id"] = "30905", ["loot_name"] = "Midnight Chestguard", ["prio"] = "Daemir",},
{["loot_id"] = "32363", ["loot_name"] = "Naaru-Blessed Life Rod", ["prio"] = "Kronkey",},
{["loot_id"] = "32370", ["loot_name"] = "Nadina's Pendant of Purity", ["prio"] = "Hashmeer, Kronkey, Saasuntwo, Cheattis, Eklm",},
{["loot_id"] = "32258", ["loot_name"] = "Naturalist's Preserving Cinch", ["prio"] = "Hashmeer, Saasuntwo, Eklm",},
{["loot_id"] = "32352", ["loot_name"] = "Naturewarden's Treads", ["prio"] = "Enkai, Schizm, Jest",},
{["loot_id"] = "32590", ["loot_name"] = "Nethervoid Cloak", ["prio"] = "Sygdot, Rezthedead",},
{["loot_id"] = "30092", ["loot_name"] = "orca-hide boots", ["prio"] = "Amoxichillin, Saasuntwo",},
{["loot_id"] = "31101", ["loot_name"] = "Pauldrons of the Forgotten Conqueror", ["prio"] = "Cheeps, Guldan, Kronkey, Sygdot, Cornholio, Rezthedead, Cheattis",},
{["loot_id"] = "31103", ["loot_name"] = "Pauldrons of the Forgotten Protector", ["prio"] = "Momochi, Roidsrage, Enkai, Hashmeer, Mitsaff, Schizm, Kravens, Saasuntwo, Verystrong, Eklm",},
{["loot_id"] = "31102", ["loot_name"] = "Pauldrons of the Forgotten Vanquisher", ["prio"] = "Jest, Jiffypop, Belialx, Amoxichillin, Frostafarion",},
{["loot_id"] = "30250", ["loot_name"] = "Pauldrons of the Vanquished Hero", ["prio"] = "Magicbulb, Norpse",},
{["loot_id"] = "32243", ["loot_name"] = "Pearl Inlaid Boots", ["prio"] = "Cheattis",},
{["loot_id"] = "30022", ["loot_name"] = "Pendant of the Perilous", ["prio"] = "Daemir",},
{["loot_id"] = "34010", ["loot_name"] = "Pepe's Shroud of Pacification", ["prio"] = "Verystrong",},
{["loot_id"] = "30883", ["loot_name"] = "Pillar of Ferocity", ["prio"] = "Jiffypop",},
{["loot_id"] = "27683", ["loot_name"] = "quagmirran's eye", ["prio"] = "Cornholio",},
{["loot_id"] = "30098", ["loot_name"] = "Razor-scale battlecloak", ["prio"] = "Daemir",},
{["loot_id"] = "32527", ["loot_name"] = "Ring of Ancient Knowledge", ["prio"] = "Jest, Jest, Guldan, Enkai, Enkai, Magicbulb, Sygdot, Schizm, Cornholio, Cornholio, Frostafarion, Norpse, Rezthedead, Rezthedead",},
{["loot_id"] = "32238", ["loot_name"] = "Ring of Calming Waves", ["prio"] = "Cheattis",},
{["loot_id"] = "32266", ["loot_name"] = "Ring of Deceitful Intent", ["prio"] = "Jiffypop, Verystrong",},
{["loot_id"] = "28791", ["loot_name"] = "Ring of the Recalcitrant", ["prio"] = "Mitsaff",},
{["loot_id"] = "30666", ["loot_name"] = "Ritssyn's lost pendant", ["prio"] = "Rezthedead",},
{["loot_id"] = "29992", ["loot_name"] = "Royal Cloak of the Sunstriders", ["prio"] = "Cheeps",},
{["loot_id"] = "30911", ["loot_name"] = "Scepter of Purification", ["prio"] = "Kronkey, Amoxichillin",},
{["loot_id"] = "30720", ["loot_name"] = "Serpent-coil Braid", ["prio"] = "Magicbulb, Norpse",},
{["loot_id"] = "32366", ["loot_name"] = "Shadowmaster's Boots", ["prio"] = "Momochi, Belialx, Mitsaff, Daemir, Kravens",},
{["loot_id"] = "32323", ["loot_name"] = "Shadowmoon Destroyer's Drape", ["prio"] = "Roidsrage, Belialx",},
{["loot_id"] = "32501", ["loot_name"] = "Shadowmoon Insignia", ["prio"] = "Jiffypop",},
{["loot_id"] = "30834", ["loot_name"] = "Shapeshifter's Signet", ["prio"] = "Daemir, Verystrong",},
{["loot_id"] = "30055", ["loot_name"] = "shoulderpads of the Stranger", ["prio"] = "Daemir",},
{["loot_id"] = "32524", ["loot_name"] = "Shroud of the Highborne", ["prio"] = "Jest, Enkai, Hashmeer, Kronkey, Amoxichillin, Magicbulb, Cornholio, Saasuntwo, Cheattis, Eklm",},
{["loot_id"] = "32239", ["loot_name"] = "Slippers of the Seacaller", ["prio"] = "Norpse, Guldan, Magicbulb, Sygdot, Cornholio, Frostafarion",},
{["loot_id"] = "30873", ["loot_name"] = "Stillwater boots", ["prio"] = "Hashmeer",},
{["loot_id"] = "32497", ["loot_name"] = "Stormrage Signet Ring", ["prio"] = "Momochi, Roidsrage, Belialx, Kravens",},
{["loot_id"] = "32584", ["loot_name"] = "Swiftheal Wraps", ["prio"] = "Kronkey",},
{["loot_id"] = "30017", ["loot_name"] = "Telonicus's Pendant of Mayhem", ["prio"] = "Mitsaff",},
{["loot_id"] = "30910", ["loot_name"] = "Tempest of Chaos", ["prio"] = "Cheeps, Guldan, Norpse",},
{["loot_id"] = "29994", ["loot_name"] = "Thalassian Wildercloak", ["prio"] = "Momochi, Mitsaff, Kravens",},
{["loot_id"] = "32254", ["loot_name"] = "The Brutalizer", ["prio"] = "Verystrong",},
{["loot_id"] = "30007", ["loot_name"] = "The Darkener's Grasp", ["prio"] = "Cheeps",},
{["loot_id"] = "28785", ["loot_name"] = "The Lightning Capacitor", ["prio"] = "Enkai, Schizm",},
{["loot_id"] = "32237", ["loot_name"] = "The Maelstrom's Fury", ["prio"] = "Enkai, Schizm",},
{["loot_id"] = "32279", ["loot_name"] = "The Seeker's Wristguards", ["prio"] = "Cheeps",},
{["loot_id"] = "32483", ["loot_name"] = "The Skull of Gul'dan", ["prio"] = "Jest, Guldan, Magicbulb, Sygdot, Cornholio, Frostafarion, Norpse",},
{["loot_id"] = "30015", ["loot_name"] = "The Sun King's Talisman", ["prio"] = "Jest, Guldan, Enkai, Schizm, Norpse, Magicbulb",},
{["loot_id"] = "32245", ["loot_name"] = "Tide-Stomper's Greaves", ["prio"] = "Cheeps",},
{["loot_id"] = "32368", ["loot_name"] = "Tome of The lightbringer", ["prio"] = "Cheeps",},
{["loot_id"] = "32332", ["loot_name"] = "Torch of the Damned", ["prio"] = "Daemir",},
{["loot_id"] = "32330", ["loot_name"] = "Totem of Ancestral Guidance", ["prio"] = "Enkai, Schizm",},
{["loot_id"] = "28523", ["loot_name"] = "Totem of Healing Rains", ["prio"] = "Hashmeer, Saasuntwo, Eklm",},
{["loot_id"] = "32349", ["loot_name"] = "Translucent Spellthread Necklace", ["prio"] = "Sygdot, Cornholio",},
{["loot_id"] = "32593", ["loot_name"] = "Treads of the Den Mother", ["prio"] = "Jiffypop",},
{["loot_id"] = "32326", ["loot_name"] = "Twisted Blades of Zarak", ["prio"] = "Roidsrage",},
{["loot_id"] = "32335", ["loot_name"] = "Unstoppable Aggressor's Ring", ["prio"] = "Roidsrage",},
{["loot_id"] = "30107", ["loot_name"] = "Vestments of the sea-witch", ["prio"] = "Guldan, Sygdot",},
{["loot_id"] = "33881", ["loot_name"] = "Vindicator's Dragonhide Bracers", ["prio"] = "Jiffypop",},
{["loot_id"] = "33923", ["loot_name"] = "Vindicator's Pendant of Triumph", ["prio"] = "Jiffypop, Verystrong",},
{["loot_id"] = "33813", ["loot_name"] = "Vindicator's Plate Bracers", ["prio"] = "Verystrong",},
{["loot_id"] = "33812", ["loot_name"] = "Vindicator's Plate Greaves", ["prio"] = "Verystrong",},
{["loot_id"] = "29279", ["loot_name"] = "Violet Signet of the Great Protector", ["prio"] = "Jiffypop",},
{["loot_id"] = "32256", ["loot_name"] = "Waistwrap of Infinity", ["prio"] = "Norpse, Rezthedead",},
{["loot_id"] = "32343", ["loot_name"] = "Wand of Prismatic Focus", ["prio"] = "Magicbulb",},
{["loot_id"] = "29982", ["loot_name"] = "Wand of the forgotten star", ["prio"] = "Guldan, Sygdot, Cornholio, Frostafarion, Rezthedead",},
{["loot_id"] = "32837", ["loot_name"] = "Warglaive of Azzinoth (mh)", ["prio"] = "Roidsrage, Belialx",},
{["loot_id"] = "32838", ["loot_name"] = "Warglaive of Azzinoth (oh)", ["prio"] = "Roidsrage, Belialx",},
{["loot_id"] = "30450", ["loot_name"] = "warp-spring coil", ["prio"] = "Belialx",},
{["loot_id"] = "32374", ["loot_name"] = "Zhar'doom, Greatstaff of the Devourer", ["prio"] = "Jest, Magicbulb, Sygdot, Cornholio, Frostafarion, Rezthedead",},
}
