Loading_bis_table = {
Loading_bis_table = {
{["loot_id"] = "34245", ["loot_name"] = "Cover of Ursol the Wise", ["prio"] = "Amoxichillin",},
{["loot_id"] = "33281", ["loot_name"] = "Brooch of Nature's Mercy", ["prio"] = "Amoxichillin, Kronkey, Saasuntwo, hashmeer",},
{["loot_id"] = "34209", ["loot_name"] = "Spaulders of Reclamation", ["prio"] = "Amoxichillin",},
{["loot_id"] = "34212", ["loot_name"] = "Sunglow Vest", ["prio"] = "Amoxichillin, Eklm, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34855", ["loot_name"] = "Belt of the Forgotten Vanquisher", ["prio"] = "Amoxichillin, Belialx, Frostafarion, Jest, Norpse, youngsice",},
{["loot_id"] = "34169", ["loot_name"] = "Breeches of Natural Aggression", ["prio"] = "Amoxichillin",},
{["loot_id"] = "34858", ["loot_name"] = "Boots of the Forgotten Vanquisher", ["prio"] = "Amoxichillin, Belialx, Frostafarion, Jest, Norpse, jiffypop, youngsice",},
{["loot_id"] = "34852", ["loot_name"] = "Bracers of the Forgotten Vanquisher", ["prio"] = "Amoxichillin, Belialx, Frostafarion, Jest, Norpse, jiffypop, youngsice",},
{["loot_id"] = "34367", ["loot_name"] = "Hands of Eternal Light", ["prio"] = "Amoxichillin",},
{["loot_id"] = "32528", ["loot_name"] = "Blessed Band of Karabor", ["prio"] = "Amoxichillin, Eklm, Eklm, Kronkey, Saasuntwo, Saasuntwo, Schizm, Schizm, hashmeer, hashmeer",},
{["loot_id"] = "29309", ["loot_name"] = "Band of the Eternal Restorer", ["prio"] = "Amoxichillin, Cheattis",},
{["loot_id"] = "29376", ["loot_name"] = "Essence of the Martyr", ["prio"] = "Amoxichillin, Cheattis, Saasuntwo, hashmeer",},
{["loot_id"] = "38288", ["loot_name"] = "Direbrew Hops", ["prio"] = "Amoxichillin",},
{["loot_id"] = "32524", ["loot_name"] = "Shroud of the Highborne", ["prio"] = "Amoxichillin, Eklm, Kronkey, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34335", ["loot_name"] = "Hammer of Sanctification", ["prio"] = "Amoxichillin, Cheattis, Eklm, Kronkey, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34206", ["loot_name"] = "Book of Highborne Hymns", ["prio"] = "Amoxichillin, Kronkey, Saasuntwo, hashmeer",},
{["loot_id"] = "27886", ["loot_name"] = "Idol of the Emerald Queen", ["prio"] = "Amoxichillin",},
{["loot_id"] = "34340", ["loot_name"] = "Dark Conjuror's Collar", ["prio"] = "Babajagga, Cornholio, Frostafarion, Jest, Rezthedead, Sygdot",},
{["loot_id"] = "34204", ["loot_name"] = "Amulet of Unfettered Magics", ["prio"] = "Babajagga, Cornholio, Enkai, Güldan, Jest, Norpse, Rezthedead, Sygdot, youngsice",},
{["loot_id"] = "31101", ["loot_name"] = "Pauldrons of the Forgotten Conqueror", ["prio"] = "Babajagga, Cheattis, Cornholio, Rezthedead, Sygdot",},
{["loot_id"] = "34364", ["loot_name"] = "Sunfire Robe", ["prio"] = "Babajagga, Cornholio, Frostafarion, Güldan, Jest, Rezthedead",},
{["loot_id"] = "34853", ["loot_name"] = "Belt of the Forgotten Conqueror", ["prio"] = "Babajagga, Cheattis, Cheeps, Cornholio, Daemir, Güldan, Kronkey, Rezthedead, Sygdot",},
{["loot_id"] = "34181", ["loot_name"] = "Leggings of Calamity", ["prio"] = "Babajagga, Cornholio, Frostafarion, Güldan, Jest, Norpse, Sygdot, youngsice",},
{["loot_id"] = "34856", ["loot_name"] = "Boots of the Forgotten Conqueror", ["prio"] = "Babajagga, Cheattis, Cheeps, Cornholio, Daemir, Güldan, Kronkey, Rezthedead, Sygdot",},
{["loot_id"] = "34848", ["loot_name"] = "Bracers of the Forgotten Conqueror", ["prio"] = "Babajagga, Cheattis, Cheeps, Cornholio, Daemir, Güldan, Kronkey, Rezthedead, Sygdot",},
{["loot_id"] = "34344", ["loot_name"] = "Handguards of Defiled Worlds", ["prio"] = "Babajagga, Cornholio, Frostafarion, Güldan, Jest, Rezthedead, Sygdot",},
{["loot_id"] = "33497", ["loot_name"] = "Mana Attuned Band", ["prio"] = "Babajagga, Frostafarion, Güldan",},
{["loot_id"] = "32527", ["loot_name"] = "Ring of Ancient Knowledge", ["prio"] = "Babajagga, Rezthedead, Sygdot",},
{["loot_id"] = "34429", ["loot_name"] = "Shifting Naaru Sliver", ["prio"] = "Babajagga, Cornholio, Enkai, Frostafarion, Güldan, Jest, Norpse, Rezthedead, Sygdot, youngsice",},
{["loot_id"] = "32483", ["loot_name"] = "The Skull of Gul'dan", ["prio"] = "Babajagga, Cornholio, Frostafarion, Güldan, Jest, Norpse, Sygdot",},
{["loot_id"] = "34242", ["loot_name"] = "Tattered Cape of Antonidas", ["prio"] = "Babajagga, Cornholio, Enkai, Frostafarion, Güldan, Jest, Norpse, Rezthedead, Sygdot, youngsice",},
{["loot_id"] = "34336", ["loot_name"] = "Sunflare", ["prio"] = "Babajagga, Cornholio, Enkai, Frostafarion, Güldan, Jest, Norpse, Rezthedead, Sygdot, youngsice",},
{["loot_id"] = "34179", ["loot_name"] = "Heart of the Pit", ["prio"] = "Babajagga, Cornholio, Enkai, Güldan, Jest, Norpse, Rezthedead, Sygdot, youngsice",},
{["loot_id"] = "34347", ["loot_name"] = "Wand of the Demonsoul", ["prio"] = "Babajagga, Cornholio, Frostafarion, Güldan, Norpse, Rezthedead, Sygdot, youngsice",},
{["loot_id"] = "34353", ["loot_name"] = "Quad Deathblow X44 Goggles", ["prio"] = "Belialx",},
{["loot_id"] = "34177", ["loot_name"] = "Clutch of Demise", ["prio"] = "Belialx, Kravens, Mitsaff, Momochi, Roidsrage",},
{["loot_id"] = "31102", ["loot_name"] = "Pauldrons of the Forgotten Vanquisher", ["prio"] = "Belialx, Frostafarion, Jest",},
{["loot_id"] = "34369", ["loot_name"] = "Carapace of Sun and Shadow", ["prio"] = "Belialx",},
{["loot_id"] = "34188", ["loot_name"] = "Leggings of the Immortal Night", ["prio"] = "Belialx, Kravens, Mitsaff, Momochi, Roidsrage, jiffypop",},
{["loot_id"] = "34370", ["loot_name"] = "Gloves of Immortal Dusk", ["prio"] = "Belialx",},
{["loot_id"] = "32497", ["loot_name"] = "Stormrage Signet Ring", ["prio"] = "Belialx, Momochi",},
{["loot_id"] = "34361", ["loot_name"] = "Hard Khorium Band", ["prio"] = "Belialx, Daemir, Kravens, Mitsaff, Momochi, Roidsrage",},
{["loot_id"] = "34428", ["loot_name"] = "Steely Naaru Sliver", ["prio"] = "Belialx, jiffypop",},
{["loot_id"] = "32505", ["loot_name"] = "Madness of the Betrayer", ["prio"] = "Belialx, Kravens",},
{["loot_id"] = "34241", ["loot_name"] = "Cloak of Unforgivable Sin", ["prio"] = "Belialx, Daemir, Kravens, Mitsaff, Momochi, Roidsrage",},
{["loot_id"] = "32837", ["loot_name"] = "Warglaive of Azzinoth", ["prio"] = "Belialx, Roidsrage",},
{["loot_id"] = "32838", ["loot_name"] = "Warglaive of Azzinoth", ["prio"] = "Belialx, Roidsrage",},
{["loot_id"] = "34334", ["loot_name"] = "Thori'dal, the Stars' Fury", ["prio"] = "Belialx, Kravens, Mitsaff, Momochi, Roidsrage",},
{["loot_id"] = "34243", ["loot_name"] = "Helm of Burning Righteousness", ["prio"] = "Cheattis, Cheeps",},
{["loot_id"] = "32370", ["loot_name"] = "Nadina's Pendant of Purity", ["prio"] = "Cheattis",},
{["loot_id"] = "34229", ["loot_name"] = "Garments of Serene Shores", ["prio"] = "Cheattis, Enkai",},
{["loot_id"] = "34167", ["loot_name"] = "Legplates of the Holy Juggernaut", ["prio"] = "Cheattis, Cheeps",},
{["loot_id"] = "34380", ["loot_name"] = "Sunblessed Gauntlets", ["prio"] = "Cheattis",},
{["loot_id"] = "32238", ["loot_name"] = "Ring of Calming Waves", ["prio"] = "Cheattis",},
{["loot_id"] = "32496", ["loot_name"] = "Memento of Tyrande", ["prio"] = "Cheattis, Eklm, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34205", ["loot_name"] = "Shroud of Redeemed Souls", ["prio"] = "Cheattis",},
{["loot_id"] = "34231", ["loot_name"] = "Aegis of Angelic Fortune", ["prio"] = "Cheattis, Eklm, Schizm",},
{["loot_id"] = "33502", ["loot_name"] = "Libram of Mending", ["prio"] = "Cheattis",},
{["loot_id"] = "34178", ["loot_name"] = "Collar of the Pit Lord", ["prio"] = "Cheeps, jiffypop",},
{["loot_id"] = "34193", ["loot_name"] = "Spaulders of the Thalassian Savior", ["prio"] = "Cheeps",},
{["loot_id"] = "34216", ["loot_name"] = "Heroic Judicator's Chestguard", ["prio"] = "Cheeps",},
{["loot_id"] = "31092", ["loot_name"] = "Gloves of the Forgotten Conqueror", ["prio"] = "Cheeps",},
{["loot_id"] = "33499", ["loot_name"] = "Signet of the Last Defender", ["prio"] = "Cheeps",},
{["loot_id"] = "34213", ["loot_name"] = "Ring of Hardened Resolve", ["prio"] = "Cheeps, jiffypop",},
{["loot_id"] = "34473", ["loot_name"] = "Commendation of Kael'thas", ["prio"] = "Cheeps",},
{["loot_id"] = "33829", ["loot_name"] = "Hex Shrunken Head", ["prio"] = "Cheeps, Enkai, Rezthedead, youngsice",},
{["loot_id"] = "34190", ["loot_name"] = "Crimson Paragon's Cover", ["prio"] = "Cheeps, jiffypop",},
{["loot_id"] = "30910", ["loot_name"] = "Tempest of Chaos", ["prio"] = "Cheeps",},
{["loot_id"] = "34185", ["loot_name"] = "Sword Breaker's Bulwark", ["prio"] = "Cheeps",},
{["loot_id"] = "32368", ["loot_name"] = "Tome of the Lightbringer", ["prio"] = "Cheeps",},
{["loot_id"] = "34362", ["loot_name"] = "Loop of Forged Power", ["prio"] = "Cornholio, Enkai, Frostafarion, Güldan, Jest, Norpse, youngsice",},
{["loot_id"] = "34230", ["loot_name"] = "Ring of Omnipotence", ["prio"] = "Cornholio, Enkai, Jest, Rezthedead, Sygdot",},
{["loot_id"] = "34244", ["loot_name"] = "Duplicitous Guise", ["prio"] = "Daemir, jiffypop",},
{["loot_id"] = "34358", ["loot_name"] = "Hard Khorium Choker", ["prio"] = "Daemir",},
{["loot_id"] = "34192", ["loot_name"] = "Pauldrons of Perseverance	", ["prio"] = "Daemir, Roidsrage",},
{["loot_id"] = "34180", ["loot_name"] = "Felfury Legplates", ["prio"] = "Daemir",},
{["loot_id"] = "34343", ["loot_name"] = "Thalassian Ranger Gauntlets", ["prio"] = "Daemir, Kravens, Mitsaff, Momochi, Roidsrage",},
{["loot_id"] = "34189", ["loot_name"] = "Band of Ruinous Delight", ["prio"] = "Daemir, Roidsrage",},
{["loot_id"] = "34427", ["loot_name"] = "Blackened Naaru Sliver", ["prio"] = "Daemir, Kravens, Mitsaff, Momochi, Roidsrage",},
{["loot_id"] = "34472", ["loot_name"] = "Shard of Contempt", ["prio"] = "Daemir",},
{["loot_id"] = "34247", ["loot_name"] = "Apolyon, the Soul-Render", ["prio"] = "Daemir",},
{["loot_id"] = "27484", ["loot_name"] = "Libram of Avengement", ["prio"] = "Daemir",},
{["loot_id"] = "34184", ["loot_name"] = "Brooch of the Highborne", ["prio"] = "Eklm, Schizm",},
{["loot_id"] = "31103", ["loot_name"] = "Pauldrons of the Forgotten Protector", ["prio"] = "Eklm, Enkai, Kravens, Mitsaff, Momochi, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34854", ["loot_name"] = "Belt of the Forgotten Protector", ["prio"] = "Eklm, Enkai, Kravens, Mitsaff, Momochi, Roidsrage, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34857", ["loot_name"] = "Boots of the Forgotten Protector", ["prio"] = "Eklm, Enkai, Kravens, Mitsaff, Momochi, Roidsrage, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34851", ["loot_name"] = "Bracers of the Forgotten Protector", ["prio"] = "Eklm, Enkai, Kravens, Mitsaff, Momochi, Roidsrage, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34430", ["loot_name"] = "Glimmering Naaru Sliver", ["prio"] = "Eklm, Kronkey, Schizm",},
{["loot_id"] = "28523", ["loot_name"] = "Totem of Healing Rains", ["prio"] = "Eklm, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34332", ["loot_name"] = "Cowl of Gul'dan", ["prio"] = "Enkai, Eklm, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34186", ["loot_name"] = "Chain Links of the Tumultuous Storm", ["prio"] = "Enkai, Eklm, Saasuntwo, Schizm, hashmeer",},
{["loot_id"] = "34350", ["loot_name"] = "Gauntlets of the Ancient Shadowmoon", ["prio"] = "Enkai, Eklm, Schizm",},
{["loot_id"] = "32330", ["loot_name"] = "Totem of Ancestral Guidance", ["prio"] = "Enkai",},
{["loot_id"] = "34359", ["loot_name"] = "Pendant of Sunfire", ["prio"] = "Frostafarion",},
{["loot_id"] = "30872", ["loot_name"] = "Chronicle of Dark Secrets", ["prio"] = "Frostafarion",},
{["loot_id"] = "31097", ["loot_name"] = "Helm of the Forgotten Conqueror", ["prio"] = "Güldan",},
{["loot_id"] = "34210", ["loot_name"] = "Amice of the Convoker", ["prio"] = "Güldan",},
{["loot_id"] = "32387", ["loot_name"] = "Idol of the Raven Goddess", ["prio"] = "Jest, jiffypop",},
{["loot_id"] = "34333", ["loot_name"] = "Coif of Alleria", ["prio"] = "Kravens, Mitsaff, Momochi, Roidsrage",},
{["loot_id"] = "34228", ["loot_name"] = "Vicious Hawkstrider Hauberk", ["prio"] = "Kravens",},
{["loot_id"] = "34887", ["loot_name"] = "Angelista's Revenge", ["prio"] = "Kravens, Mitsaff",},
{["loot_id"] = "34183", ["loot_name"] = "Shivering Felspine", ["prio"] = "Kravens, Mitsaff",},
{["loot_id"] = "34339", ["loot_name"] = "Cowl of Light's Purity", ["prio"] = "Kronkey",},
{["loot_id"] = "34202", ["loot_name"] = "Shawl of Wonderment", ["prio"] = "Kronkey",},
{["loot_id"] = "34233", ["loot_name"] = "Robes of Faltered Light", ["prio"] = "Kronkey, Norpse, youngsice",},
{["loot_id"] = "34170", ["loot_name"] = "Pantaloons of Calming Strife", ["prio"] = "Kronkey, Rezthedead",},
{["loot_id"] = "34342", ["loot_name"] = "Handguards of the Dawn", ["prio"] = "Kronkey, Norpse, youngsice",},
{["loot_id"] = "34363", ["loot_name"] = "Ring of Flowing Life", ["prio"] = "Kronkey",},
{["loot_id"] = "35750", ["loot_name"] = "Redeemer's Alchemist Stone", ["prio"] = "Kronkey",},
{["loot_id"] = "34348", ["loot_name"] = "Wand of Cleansing Light", ["prio"] = "Kronkey",},
{["loot_id"] = "28830", ["loot_name"] = "Dragonspine Trophy", ["prio"] = "Mitsaff, Roidsrage",},
{["loot_id"] = "33831", ["loot_name"] = "Berserker's Call", ["prio"] = "Momochi",},
{["loot_id"] = "34331", ["loot_name"] = "Hand of the Deceiver", ["prio"] = "Momochi",},
{["loot_id"] = "34203", ["loot_name"] = "Grip of Mannoroth", ["prio"] = "Momochi",},
{["loot_id"] = "30244", ["loot_name"] = "Helm of the Vanquished Hero", ["prio"] = "Norpse, youngsice",},
{["loot_id"] = "30250", ["loot_name"] = "Pauldrons of the Vanquished Hero", ["prio"] = "Norpse, youngsice",},
{["loot_id"] = "29305", ["loot_name"] = "Band of the Eternal Sage", ["prio"] = "Norpse, youngsice",},
{["loot_id"] = "34376", ["loot_name"] = "Sun-Drenched Scale Gloves", ["prio"] = "Saasuntwo, hashmeer",},
{["loot_id"] = "34232", ["loot_name"] = "Fel Conqueror Raiments", ["prio"] = "Sygdot",},
{["loot_id"] = "34195", ["loot_name"] = "Shoulderpads of Vehemence", ["prio"] = "jiffypop",},
{["loot_id"] = "34211", ["loot_name"] = "Harness of Carnal Instinct", ["prio"] = "jiffypop, Daemir, Mitsaff, Momochi, Roidsrage",},
{["loot_id"] = "35152", ["loot_name"] = "Guardian's Dragonhide Belt", ["prio"] = "jiffypop",},
{["loot_id"] = "34234", ["loot_name"] = "Shadowed Gauntlets of Paroxysm", ["prio"] = "jiffypop",},
{["loot_id"] = "34888", ["loot_name"] = "Ring of the Stalwart Protector", ["prio"] = "jiffypop",},
{["loot_id"] = "32501", ["loot_name"] = "Shadowmoon Insignia", ["prio"] = "jiffypop",},
{["loot_id"] = "34198", ["loot_name"] = "Stanchion of Primal Instinct", ["prio"] = "jiffypop",},
{["loot_id"] = "34664", ["loot_name"] = "Sunmote", ["prio"] = "Amoxichillin, Cheeps (3), Daemir (2), Eklm (3), Enkai, hashmeer (2), jiffypop (4), Mitsaff, Momochi, Norpse (2), Rezthedead, Roidsrage (2), Schizm (3), youngsice (2)",},
}
