Donkey_loot_table = {
{["loot_id"] = "19345", ["loot_name"] = "Aegis of Preservation", ["prio"] = "*PVP*",},
{["loot_id"] = "18823", ["loot_name"] = "Aged Core Leather Gloves", ["prio"] = "Prot Warrior, Dagger Rogue > Sword Rogue, Fury Warrior",},
{["loot_id"] = "21702", ["loot_name"] = "Amulet of Foul Warding", ["prio"] = "Soakers",},
{["loot_id"] = "21608", ["loot_name"] = "Amulet of Vek'nilash", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "18703", ["loot_name"] = "Ancient Petrified Leaf", ["prio"] = "Hunters",},
{["loot_id"] = "21650", ["loot_name"] = "Ancient Qiraji Ripper", ["prio"] = "Voxxtelum",},
{["loot_id"] = "21690", ["loot_name"] = "Angelista's Charm", ["prio"] = "Healers",},
{["loot_id"] = "19388", ["loot_name"] = "Angelista's Grasp", ["prio"] = "Warlock > Mage, Shadow Priest",},
{["loot_id"] = "21695", ["loot_name"] = "Angelista's Touch", ["prio"] = "Tanks",},
{["loot_id"] = "19376", ["loot_name"] = "Archimtiros' Ring of Reckoning", ["prio"] = "Feral Tank > Prot Warrior > Rogue, Hunter, Fury Warrior",},
{["loot_id"] = "19361", ["loot_name"] = "Ashjre'thul, Crossbow of Smiting", ["prio"] = "Ganggang",},
{["loot_id"] = "19364", ["loot_name"] = "Ashkandi, Greatsword of the Brotherhood", ["prio"] = "Thomasbot",},
{["loot_id"] = "17105", ["loot_name"] = "Aurastone Hammer", ["prio"] = "Resto Shaman, Resto Druid > Heal Priest",},
{["loot_id"] = "17103", ["loot_name"] = "Azuresong Mageblade", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "21670", ["loot_name"] = "Badge of the Swarmguard", ["prio"] = "Hunter, Rogue, Enhance > Fury Warrior",},
{["loot_id"] = "17063", ["loot_name"] = "Band of Accuria", ["prio"] = "All Hit Boys",},
{["loot_id"] = "19434", ["loot_name"] = "Band of Dark Dominion", ["prio"] = "Shadow Priest, Warlock",},
{["loot_id"] = "19403", ["loot_name"] = "Band of Forced Concentration", ["prio"] = "Mage, Warlock > Shadow Priest",},
{["loot_id"] = "22961", ["loot_name"] = "Band of Reanimation", ["prio"] = "Hunter",},
{["loot_id"] = "23031", ["loot_name"] = "Band of the Inevitable", ["prio"] = "Mage, Shadow Priest",},
{["loot_id"] = "22939", ["loot_name"] = "Band of Unanswered Prayers", ["prio"] = "Heal Priest, Resto Druid > Resto Shaman",},
{["loot_id"] = "23038", ["loot_name"] = "Band of Unnatural Forces", ["prio"] = "Melee > Hunter",},
{["loot_id"] = "21635", ["loot_name"] = "Barb of the Sand Reaver", ["prio"] = "Hunter",},
{["loot_id"] = "21664", ["loot_name"] = "Barbed Choker", ["prio"] = "Fury Warrior",},
{["loot_id"] = "22734", ["loot_name"] = "Base of Atiesh", ["prio"] = "Feral Druid OS Garbage",},
{["loot_id"] = "21708", ["loot_name"] = "Beetle Scaled Wristguards", ["prio"] = "Soakers",},
{["loot_id"] = "21586", ["loot_name"] = "Belt of Never-ending Agony", ["prio"] = "Rogue > Feral",},
{["loot_id"] = "21500", ["loot_name"] = "Belt of the Inquisition", ["prio"] = "Healers",},
{["loot_id"] = "21503", ["loot_name"] = "Belt of the Sand Reaver", ["prio"] = "Prot Warrior",},
{["loot_id"] = "19897", ["loot_name"] = "Betrayer's Boots", ["prio"] = "Warlock",},
{["loot_id"] = "21682", ["loot_name"] = "Bile-Covered Gauntlets", ["prio"] = "Soakers",},
{["loot_id"] = "18563", ["loot_name"] = "Bindings of the Windseeker 1", ["prio"] = "Verystrong",},
{["loot_id"] = "18564", ["loot_name"] = "Bindings of the Windseeker 2", ["prio"] = "Verystrong",},
{["loot_id"] = "19373", ["loot_name"] = "Black Brood Pauldrons", ["prio"] = "Hunter, Enhance",},
{["loot_id"] = "17072", ["loot_name"] = "Blastershot Launcher", ["prio"] = "Fury Warrior, Rogue",},
{["loot_id"] = "17076", ["loot_name"] = "Bonereaver's Edge", ["prio"] = "2H Fury Warrior > Prot Warrior",},
{["loot_id"] = "23073", ["loot_name"] = "Boots of Displacement", ["prio"] = "Feral, Rogue",},
{["loot_id"] = "21600", ["loot_name"] = "Boots of Epiphany", ["prio"] = "Shadow Priest > Heal Priest",},
{["loot_id"] = "19437", ["loot_name"] = "Boots of Pure Thought", ["prio"] = "Resto Druid, Heal Priest, Resto Shaman",},
{["loot_id"] = "21688", ["loot_name"] = "Boots of the Fallen Hero", ["prio"] = "Fury Warrior (w/o Chromatic Boots)",},
{["loot_id"] = "19381", ["loot_name"] = "Boots of the Shadow Flame", ["prio"] = "All",},
{["loot_id"] = "21706", ["loot_name"] = "Boots of the Unwavering Will", ["prio"] = "Prot Warrior",},
{["loot_id"] = "21493", ["loot_name"] = "Boots of the Vanguard", ["prio"] = "Feral > Rogue",},
{["loot_id"] = "21478", ["loot_name"] = "Bow of Taut Sinew", ["prio"] = "Soakers",},
{["loot_id"] = "21604", ["loot_name"] = "Bracelets of Royal Redemption", ["prio"] = "Resto Druid, Heal Priest",},
{["loot_id"] = "19374", ["loot_name"] = "Bracers of Arcane Accuracy", ["prio"] = "Warlock, Mage > Shadow Priest",},
{["loot_id"] = "21457", ["loot_name"] = "Bracers of Brutality", ["prio"] = "Prot Warrior > Fury Warrior",},
{["loot_id"] = "21814", ["loot_name"] = "Breastplate of Annihilation", ["prio"] = "Fury Warrior",},
{["loot_id"] = "22800", ["loot_name"] = "Brimstone Staff", ["prio"] = "Mage, Warlock (2H, No Atiesh)",},
{["loot_id"] = "18832", ["loot_name"] = "Brutality Blade", ["prio"] = "Sword Rogue, 1H Fury Warrior (non-Orc) > Hunter, Prot Warrior",},
{["loot_id"] = "21611", ["loot_name"] = "Burrower Bracers", ["prio"] = "Shadow Priest > Mage, Warlock",},
{["loot_id"] = "21485", ["loot_name"] = "Buru's Skull Fragment", ["prio"] = "Prot Warrior",},
{["loot_id"] = "21697", ["loot_name"] = "Cape of the Trinity", ["prio"] = "Casters w/o Broodlord Cloak",},
{["loot_id"] = "20929", ["loot_name"] = "Carapace of the Old God", ["prio"] = "(Chest) Resto Shaman > Prot Warrior > Rogue > Fury Warrior",},
{["loot_id"] = "19140", ["loot_name"] = "Cauterizing Band", ["prio"] = "Heal Priest, Resto Shaman, Resto Druid",},
{["loot_id"] = "18814", ["loot_name"] = "Choker of the Fire Lord", ["prio"] = "Caster DPS > Healers",},
{["loot_id"] = "19387", ["loot_name"] = "Chromatic Boots", ["prio"] = "Prot Warrior, Fury Warrior",},
{["loot_id"] = "19352", ["loot_name"] = "Chromatically Tempered Sword", ["prio"] = "Sword Rogue, Fury Warrior (non-Orc) > Prot Warrior, Dagger Rogue",},
{["loot_id"] = "19432", ["loot_name"] = "Circle of Applied Force", ["prio"] = "All > Hunter",},
{["loot_id"] = "19347", ["loot_name"] = "Claw of Chromaggus", ["prio"] = "All > Heal Priest",},
{["loot_id"] = "19365", ["loot_name"] = "Claw of the Black Drake", ["prio"] = "Fury Warrior > Rogue",},
{["loot_id"] = "22813", ["loot_name"] = "Claymore of Unholy Might", ["prio"] = "Warrior",},
{["loot_id"] = "21583", ["loot_name"] = "Cloak of Clarity", ["prio"] = "Healers",},
{["loot_id"] = "21701", ["loot_name"] = "Cloak of Concentrated Hatred", ["prio"] = "Rogue, Enhance > Hunter, Fury Warrior",},
{["loot_id"] = "19857", ["loot_name"] = "Cloak of Consumption", ["prio"] = "Mage",},
{["loot_id"] = "19436", ["loot_name"] = "Cloak of Draconic Might", ["prio"] = "Feral, Fury Warrior, Rogue > Prot Warrior, Hunter",},
{["loot_id"] = "19398", ["loot_name"] = "Cloak of Firemaw", ["prio"] = "Melee",},
{["loot_id"] = "22960", ["loot_name"] = "Cloak of Suturing", ["prio"] = "Healers",},
{["loot_id"] = "19378", ["loot_name"] = "Cloak of the Brood Lord", ["prio"] = "Mage, Shadow Priest > Warlock",},
{["loot_id"] = "22731", ["loot_name"] = "Cloak of the Devoured", ["prio"] = "Mage, Warlock > Shadow Priest",},
{["loot_id"] = "23050", ["loot_name"] = "Cloak of the Necropolis", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "17102", ["loot_name"] = "Cloak of the Shrouded Mists", ["prio"] = "Tanks > DPS",},
{["loot_id"] = "21627", ["loot_name"] = "Cloak of Untold Secrets", ["prio"] = "Twin Emps Warlock Tank",},
{["loot_id"] = "18806", ["loot_name"] = "Core Forged Greaves", ["prio"] = "Prot Warrior, Fury Warrior",},
{["loot_id"] = "18805", ["loot_name"] = "Core Hound Tooth", ["prio"] = "Prot Warrior, Dagger Rogue > Hunter",},
{["loot_id"] = "22691", ["loot_name"] = "Corrupted Ashbringer", ["prio"] = "Meme",},
{["loot_id"] = "21669", ["loot_name"] = "Creeping Vine Helm", ["prio"] = "Resto Druid > Resto Shaman",},
{["loot_id"] = "17077", ["loot_name"] = "Crimson Shocker", ["prio"] = "Priest",},
{["loot_id"] = "21459", ["loot_name"] = "Crossbow of Imminent Doom", ["prio"] = "Prot Warrior",},
{["loot_id"] = "18817", ["loot_name"] = "Crown of Destruction", ["prio"] = "Enhance Shaman, Hunter > Fury Warrior",},
{["loot_id"] = "19363", ["loot_name"] = "Crul'shorukh, Edge of Chaos", ["prio"] = "Fury Warrior (Orc), Prot Warrior > Hunter",},
{["loot_id"] = "22938", ["loot_name"] = "Cryptfiend Silk Cloak", ["prio"] = "Tanks",},
{["loot_id"] = "23220", ["loot_name"] = "Crystal Webbed Robe", ["prio"] = "Shadow Priest",},
{["loot_id"] = "21134", ["loot_name"] = "Dark Edge of Insanity", ["prio"] = "Fury Warrior",},
{["loot_id"] = "21585", ["loot_name"] = "Dark Storm Gauntlets", ["prio"] = "Warlock, Mage",},
{["loot_id"] = "23075", ["loot_name"] = "Death's Bargain", ["prio"] = "Resto Shaman",},
{["loot_id"] = "21126", ["loot_name"] = "Death's Sting", ["prio"] = "Dagger Rogue > Prot Warrior (no TF)",},
{["loot_id"] = "22370", ["loot_name"] = "Desecrated Belt", ["prio"] = "None",},
{["loot_id"] = "22369", ["loot_name"] = "Desecrated Bindings", ["prio"] = "None",},
{["loot_id"] = "22365", ["loot_name"] = "Desecrated Boots", ["prio"] = "None",},
{["loot_id"] = "22355", ["loot_name"] = "Desecrated Bracers", ["prio"] = "Prot Warrior, Rogue",},
{["loot_id"] = "22349", ["loot_name"] = "Desecrated Breastplate", ["prio"] = "Prot Warrior, Rogue",},
{["loot_id"] = "22367", ["loot_name"] = "Desecrated Circlet", ["prio"] = "Priest, Mage, Warlock",},
{["loot_id"] = "22357", ["loot_name"] = "Desecrated Gauntlets", ["prio"] = "Prot Warrior, Rogue",},
{["loot_id"] = "22363", ["loot_name"] = "Desecrated Girdle", ["prio"] = "Hunter, Druid, Shaman",},
{["loot_id"] = "22371", ["loot_name"] = "Desecrated Gloves", ["prio"] = "Priest, Mage, Warlock",},
{["loot_id"] = "22364", ["loot_name"] = "Desecrated Handguards", ["prio"] = "Druid, Hunter, Shaman",},
{["loot_id"] = "22360", ["loot_name"] = "Desecrated Headpiece", ["prio"] = "None",},
{["loot_id"] = "22353", ["loot_name"] = "Desecrated Helmet", ["prio"] = "Prot Warrior, Rogue",},
{["loot_id"] = "22366", ["loot_name"] = "Desecrated Leggings", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "22359", ["loot_name"] = "Desecrated Legguards", ["prio"] = "None",},
{["loot_id"] = "22352", ["loot_name"] = "Desecrated Legplates", ["prio"] = "Prot Warrior, Rogue",},
{["loot_id"] = "22354", ["loot_name"] = "Desecrated Pauldrons", ["prio"] = "Prot Warrior, Rogue",},
{["loot_id"] = "22351", ["loot_name"] = "Desecrated Robe", ["prio"] = "Warlock, Mage > Priest",},
{["loot_id"] = "22358", ["loot_name"] = "Desecrated Sabatons", ["prio"] = "Prot Warrior, Rogue",},
{["loot_id"] = "22372", ["loot_name"] = "Desecrated Sandals", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "22368", ["loot_name"] = "Desecrated Shoulderpads", ["prio"] = "Priest, Warlock > Mage",},
{["loot_id"] = "22361", ["loot_name"] = "Desecrated Spaulders", ["prio"] = "Druid, Shaman, Hunter",},
{["loot_id"] = "22350", ["loot_name"] = "Desecrated Tunic", ["prio"] = "Druid, Shaman, Hunter",},
{["loot_id"] = "22356", ["loot_name"] = "Desecrated Waistguard", ["prio"] = "Prot Warrior, Rogue",},
{["loot_id"] = "22362", ["loot_name"] = "Desecrated Wristguards", ["prio"] = "Hunter, Druid, Shaman",},
{["loot_id"] = "20628", ["loot_name"] = "Deviate Growth Cap", ["prio"] = "Resto Druid, Resto Shaman",},
{["loot_id"] = "21615", ["loot_name"] = "Don Rigoberto's Lost Hat", ["prio"] = "Heal Priest > Resto Druid",},
{["loot_id"] = "19362", ["loot_name"] = "Doom's Edge", ["prio"] = "Fury Warrior (Orc), Prot Warrior > Hunter",},
{["loot_id"] = "22821", ["loot_name"] = "Doomfinger", ["prio"] = "Mage",},
{["loot_id"] = "19354", ["loot_name"] = "Draconic Avenger", ["prio"] = "Fury Warrior, Enhanceance",},
{["loot_id"] = "19358", ["loot_name"] = "Draconic Maul", ["prio"] = "Feral > Rest",},
{["loot_id"] = "17107", ["loot_name"] = "Dragon's Blood Cape", ["prio"] = "All > Hunter",},
{["loot_id"] = "19367", ["loot_name"] = "Dragon's Touch", ["prio"] = "Priest",},
{["loot_id"] = "19368", ["loot_name"] = "Dragonbreath Hand Cannon", ["prio"] = "Prot Warrior, Rogue > Hunter, Fury Warrior",},
{["loot_id"] = "19346", ["loot_name"] = "Dragonfang Blade", ["prio"] = "Prot Warrior, Dagger Rogue",},
{["loot_id"] = "19406", ["loot_name"] = "Drake Fang Talisman", ["prio"] = "All > Hunter",},
{["loot_id"] = "19353", ["loot_name"] = "Drake Talon Cleaver", ["prio"] = "Fury Warrior, Enhance",},
{["loot_id"] = "19394", ["loot_name"] = "Drake Talon Pauldrons", ["prio"] = "Warrior",},
{["loot_id"] = "17066", ["loot_name"] = "Drillborer Disk", ["prio"] = "Prot Warrior",},
{["loot_id"] = "17073", ["loot_name"] = "Earthshaker", ["prio"] = "Fury Warrior, Enhance",},
{["loot_id"] = "19407", ["loot_name"] = "Ebony Flame Gloves", ["prio"] = "Shadow Priest > Warlock",},
{["loot_id"] = "19349", ["loot_name"] = "Elementium Reinforced Bulwark", ["prio"] = "Verystrong",},
{["loot_id"] = "19386", ["loot_name"] = "Elementium Threaded Cloak", ["prio"] = "Tanks",},
{["loot_id"] = "19435", ["loot_name"] = "Essence Gatherer", ["prio"] = "Priest > Mage, Warlock",},
{["loot_id"] = "21221", ["loot_name"] = "Eye of C'Thun", ["prio"] = "Caster DPS",},
{["loot_id"] = "23001", ["loot_name"] = "Eye of Diminution", ["prio"] = "Warlock > Mage",},
{["loot_id"] = "17204", ["loot_name"] = "Eye of Sulfuras", ["prio"] = "Hunter Weapon lol",},
{["loot_id"] = "23047", ["loot_name"] = "Eye of the Dead", ["prio"] = "Healers",},
{["loot_id"] = "22730", ["loot_name"] = "Eyestalk Waist Cord", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "21647", ["loot_name"] = "Fetish of the Sand Reaver", ["prio"] = "Kraggus",},
{["loot_id"] = "18803", ["loot_name"] = "Finkle's Lava Dredger", ["prio"] = "Resto Druid, Shaman",},
{["loot_id"] = "19142", ["loot_name"] = "Fire Runed Grimoire", ["prio"] = "Anyone",},
{["loot_id"] = "19139", ["loot_name"] = "Fireguard Shoulders", ["prio"] = "Tanks",},
{["loot_id"] = "19400", ["loot_name"] = "Firemaw's Clutch", ["prio"] = "Shadow Priest > Mage, Warlock > Rest",},
{["loot_id"] = "18811", ["loot_name"] = "Fireproof Cloak", ["prio"] = "Tanks",},
{["loot_id"] = "19143", ["loot_name"] = "Flameguard Gauntlets", ["prio"] = "Fury Warrior > Prot Warrior",},
{["loot_id"] = "18861", ["loot_name"] = "Flamewaker Legplates", ["prio"] = "Prot Warrior > Fury Warrior",},
{["loot_id"] = "21838", ["loot_name"] = "Garb of Royal Ascension", ["prio"] = "Twin Emps Warlock Tank",},
{["loot_id"] = "21581", ["loot_name"] = "Gauntlets of Annihilation", ["prio"] = "Fury Warrior > Prot Warrior",},
{["loot_id"] = "21624", ["loot_name"] = "Gauntlets of Kalimdor", ["prio"] = "Ele Shaman",},
{["loot_id"] = "21469", ["loot_name"] = "Gauntlets of Southwind", ["prio"] = "Boomkin",},
{["loot_id"] = "21674", ["loot_name"] = "Gauntlets of Steadfast Determination", ["prio"] = "Fury-Prot",},
{["loot_id"] = "21479", ["loot_name"] = "Gauntlets of the Immovable", ["prio"] = "Prot Warrior",},
{["loot_id"] = "23057", ["loot_name"] = "Gem of Trapped Innocents", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "23226", ["loot_name"] = "Ghoul Skin Tunic", ["prio"] = "Feral",},
{["loot_id"] = "23663", ["loot_name"] = "Girdle of Elemental Fury", ["prio"] = "Shaman",},
{["loot_id"] = "23219", ["loot_name"] = "Girdle of the Mentor", ["prio"] = "Warrior",},
{["loot_id"] = "23032", ["loot_name"] = "Glacial Headdress", ["prio"] = "Frost Resist",},
{["loot_id"] = "22968", ["loot_name"] = "Glacial Mantle", ["prio"] = "Frost Resist",},
{["loot_id"] = "21689", ["loot_name"] = "Gloves of Ebru", ["prio"] = "Boomkin",},
{["loot_id"] = "21672", ["loot_name"] = "Gloves of Enforcement", ["prio"] = "Rogue, Enhance > Feral",},
{["loot_id"] = "19369", ["loot_name"] = "Gloves of Rapid Evolution", ["prio"] = "Healers",},
{["loot_id"] = "21605", ["loot_name"] = "Gloves of the Hidden Temple", ["prio"] = "Feral Tank",},
{["loot_id"] = "18808", ["loot_name"] = "Gloves of the Hypnotic Flame", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "21619", ["loot_name"] = "Gloves of the Messiah", ["prio"] = "Heal Priest > Shaman, Druid",},
{["loot_id"] = "22981", ["loot_name"] = "Gluth's Missing Collar", ["prio"] = "Prot Warrior",},
{["loot_id"] = "23040", ["loot_name"] = "Glyph of Deflection", ["prio"] = "Prot Warrior",},
{["loot_id"] = "21607", ["loot_name"] = "Grasp of the Fallen Emperor", ["prio"] = "Elemental Shaman",},
{["loot_id"] = "21582", ["loot_name"] = "Grasp of the Old God", ["prio"] = "Heal Priest > Resto Druid",},
{["loot_id"] = "23054", ["loot_name"] = "Gressil, Dawn of Ruin", ["prio"] = "Sword Rogue",},
{["loot_id"] = "19939", ["loot_name"] = "Gri'lek's Blood", ["prio"] = "Resto Shaman",},
{["loot_id"] = "21693", ["loot_name"] = "Guise of the Devourer", ["prio"] = "Feral > Rogue",},
{["loot_id"] = "19853", ["loot_name"] = "Gurubashi Dwarf Destroyer", ["prio"] = "Dwarf Destroyers",},
{["loot_id"] = "17071", ["loot_name"] = "Gutgore Ripper", ["prio"] = "Dagger Rogue > Rest",},
{["loot_id"] = "23028", ["loot_name"] = "Hailstone Band", ["prio"] = "Frost Resist",},
{["loot_id"] = "23056", ["loot_name"] = "Hammer of the Twisting Nether", ["prio"] = "Healers",},
{["loot_id"] = "23044", ["loot_name"] = "Harbinger of Doom", ["prio"] = "Hunter > Dagger Rogue",},
{["loot_id"] = "22816", ["loot_name"] = "Hatchet of Sundered Bone", ["prio"] = "Fury Warrior (Orc) > Hunter > Fury Warrior (non-Orc)",},
{["loot_id"] = "19002", ["loot_name"] = "Head of Nefarian", ["prio"] = "Tanks, Melee",},
{["loot_id"] = "21220", ["loot_name"] = "Head of Ossirian the Unscarred", ["prio"] = "Healers",},
{["loot_id"] = "18879", ["loot_name"] = "Heavy Dark Iron Ring", ["prio"] = "Tanks",},
{["loot_id"] = "21460", ["loot_name"] = "Helm of Domination", ["prio"] = "Prot Warrior",},
{["loot_id"] = "19372", ["loot_name"] = "Helm of Endless Rage", ["prio"] = "Prot Warrior, Fury Warrior",},
{["loot_id"] = "21618", ["loot_name"] = "Hive Defiler Wristguards", ["prio"] = "Fury Warrior",},
{["loot_id"] = "21645", ["loot_name"] = "Hive Tunneler's Boots", ["prio"] = "Bears w/o Nef Boots > Rogue",},
{["loot_id"] = "20933", ["loot_name"] = "Husk of the Old God", ["prio"] = "(Chest) Shadow Priest > Mage, Warlock",},
{["loot_id"] = "23014", ["loot_name"] = "Iblis, Blade of the Fallen Seraph", ["prio"] = "Sword Rogue > Hunter",},
{["loot_id"] = "23019", ["loot_name"] = "Icebane Helmet", ["prio"] = "Frost Resist",},
{["loot_id"] = "22940", ["loot_name"] = "Icebane Pauldrons", ["prio"] = "Frost Resist",},
{["loot_id"] = "23033", ["loot_name"] = "Icy Scale Coif", ["prio"] = "Frost Resist",},
{["loot_id"] = "22967", ["loot_name"] = "Icy Scale Spaulders", ["prio"] = "Frost Resist",},
{["loot_id"] = "21232", ["loot_name"] = "Imperial Qiraji Armaments", ["prio"] = "Dagger Rogue, 1H Fury Warrior (Orc) > Prot Warrior",},
{["loot_id"] = "21237", ["loot_name"] = "Imperial Qiraji Regalia", ["prio"] = "Feral > Casters (Staff)",},
{["loot_id"] = "23570", ["loot_name"] = "Jom Gabbar", ["prio"] = "Rogue, Hunter > Fury Warrior",},
{["loot_id"] = "22802", ["loot_name"] = "Kingsfall", ["prio"] = "Dagger Rogue > Hunter",},
{["loot_id"] = "22954", ["loot_name"] = "Kiss of the Spider", ["prio"] = "Rogue, Fury Warrior",},
{["loot_id"] = "23557", ["loot_name"] = "Larvae of the Great Worm", ["prio"] = "Rogue, Fury Warrior",},
{["loot_id"] = "23071", ["loot_name"] = "Leggings of Apocalypse", ["prio"] = "Enhance > Feral > Fury Warrior",},
{["loot_id"] = "23665", ["loot_name"] = "Leggings of Elemental Fury", ["prio"] = "Elemental Shaman",},
{["loot_id"] = "21698", ["loot_name"] = "Leggings of Immersion", ["prio"] = "Resto Druid",},
{["loot_id"] = "23070", ["loot_name"] = "Leggings of Polarity", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "21461", ["loot_name"] = "Leggings of the Black Blizzard", ["prio"] = "Mage > Warlock",},
{["loot_id"] = "21676", ["loot_name"] = "Leggings of the Festering Swarm", ["prio"] = "Mage",},
{["loot_id"] = "23068", ["loot_name"] = "Legplates of Carnage", ["prio"] = "Fury Warrior",},
{["loot_id"] = "21495", ["loot_name"] = "Legplates of the Qiraji Command", ["prio"] = "Fury Warrior",},
{["loot_id"] = "19341", ["loot_name"] = "Lifegiving Gem", ["prio"] = "Prot Warrior",},
{["loot_id"] = "23042", ["loot_name"] = "Loatheb's Reflection", ["prio"] = "Trinket of Binding",},
{["loot_id"] = "19360", ["loot_name"] = "Lok'amir il Romathis", ["prio"] = "Resto Shaman, Resto Druid, Shadow Priest, Heal Priest (if they have Lei)",},
{["loot_id"] = "22804", ["loot_name"] = "Maexxna's Fang", ["prio"] = "Dagger Rogue, Prot Warrior",},
{["loot_id"] = "19351", ["loot_name"] = "Maladath, Runed Blade of the Black Flight ", ["prio"] = "Sword Rogue, Fury Warrior (non-Orc) > Dagger Rogue, Prot Warrior",},
{["loot_id"] = "19405", ["loot_name"] = "Malfurion's Blessed Bulwark", ["prio"] = "Feral, Fury Warrior, Enhance > Rogue",},
{["loot_id"] = "22943", ["loot_name"] = "Malice Stone Pendant", ["prio"] = "None",},
{["loot_id"] = "17106", ["loot_name"] = "Malistar's Defender", ["prio"] = "Shaman",},
{["loot_id"] = "19136", ["loot_name"] = "Mana Igniting Cord", ["prio"] = "Mage, Warlock > Rest",},
{["loot_id"] = "18872", ["loot_name"] = "Manastorm Leggings", ["prio"] = "Healers",},
{["loot_id"] = "19370", ["loot_name"] = "Mantle of the Blackwing Cabal", ["prio"] = "Shadow Priest > Mage > Warlock, Healers",},
{["loot_id"] = "21665", ["loot_name"] = "Mantle of Wicked Revenge", ["prio"] = "Feral > Enhance > Fury Warrior",},
{["loot_id"] = "22732", ["loot_name"] = "Mark of C'Thun", ["prio"] = "Tanks",},
{["loot_id"] = "22809", ["loot_name"] = "Maul of the Redeemed Crusader", ["prio"] = "None",},
{["loot_id"] = "17065", ["loot_name"] = "Medallion of Steadfast Might", ["prio"] = "Tanks",},
{["loot_id"] = "22803", ["loot_name"] = "Midnight Haze", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "22798", ["loot_name"] = "Might of Menethil", ["prio"] = "Enhance > Fury Warrior",},
{["loot_id"] = "23548", ["loot_name"] = "Might of the Scourge", ["prio"] = "Melee, Hunter > Prot Warrior",},
{["loot_id"] = "19375", ["loot_name"] = "Mish'undare, Circlet of the Mind Flayer", ["prio"] = "Mage, Warlock > Rest",},
{["loot_id"] = "23221", ["loot_name"] = "Misplaced Servo Arm", ["prio"] = "Prot Warrior",},
{["loot_id"] = "19947", ["loot_name"] = "Nat Pagle's Broken Reel", ["prio"] = "Taunt Warrior for 4H Taunt Hit",},
{["loot_id"] = "23036", ["loot_name"] = "Necklace of Necropsy", ["prio"] = "Healers",},
{["loot_id"] = "21678", ["loot_name"] = "Necklace of Purity", ["prio"] = "Soakers",},
{["loot_id"] = "23069", ["loot_name"] = "Necro-Knight's Garb", ["prio"] = "None",},
{["loot_id"] = "19379", ["loot_name"] = "Neltharion's Tear", ["prio"] = "Twin Emps Warlock Tank > Mage, Shadow Priest",},
{["loot_id"] = "21856", ["loot_name"] = "Neretzek, The Blood Drinker", ["prio"] = "2H Fury Warrior",},
{["loot_id"] = "22812", ["loot_name"] = "Nerubian Slavemaker", ["prio"] = "Hunter",},
{["loot_id"] = "23029", ["loot_name"] = "Noth's Frigid Heart", ["prio"] = "Resto Druid",},
{["loot_id"] = "18822", ["loot_name"] = "Obsidian Edged Blade", ["prio"] = "2H Fury Warrior > Prot Warrior",},
{["loot_id"] = "19137", ["loot_name"] = "Onslaught Girdle", ["prio"] = "Warrior",},
{["loot_id"] = "21691", ["loot_name"] = "Ooze-ridden Gauntlets", ["prio"] = "Soakers",},
{["loot_id"] = "20927", ["loot_name"] = "Ouro�s Intact Hide", ["prio"] = "Prot Warrior > Rogue, Shadow Priest > Fury Warrior, Mage",},
{["loot_id"] = "21639", ["loot_name"] = "Pauldrons of the Unrelenting", ["prio"] = "Prot Warrior",},
{["loot_id"] = "22947", ["loot_name"] = "Pendant of Forgotten Names", ["prio"] = "DE",},
{["loot_id"] = "19371", ["loot_name"] = "Pendant of the Fallen Dragon", ["prio"] = "Resto Shaman > Heal Priest, Resto Druid",},
{["loot_id"] = "21700", ["loot_name"] = "Pendant of the Qiraji Guardian", ["prio"] = "Tanks",},
{["loot_id"] = "18816", ["loot_name"] = "Perdition's Blade", ["prio"] = "Dagger Rogue, Prot Warrior > Sword Rogue, Fury Warrior",},
{["loot_id"] = "23000", ["loot_name"] = "Plated Abomination Ribcage", ["prio"] = "Fury Warrior",},
{["loot_id"] = "23020", ["loot_name"] = "Polar Helmet", ["prio"] = "Frost Resist",},
{["loot_id"] = "23545", ["loot_name"] = "Power of the Scourge", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "23035", ["loot_name"] = "Preceptor's Hat", ["prio"] = "Shadow Priest > Mage, Warlock",},
{["loot_id"] = "19377", ["loot_name"] = "Prestor's Talisman of Connivery", ["prio"] = "Rogue, Cat, Hunter > Bear, Prot Warrior",},
{["loot_id"] = "19382", ["loot_name"] = "Pure Elementium Band", ["prio"] = "Healers",},
{["loot_id"] = "20928", ["loot_name"] = "Qiraji Bindings of Command", ["prio"] = "(Shoulders & Feet) Prot Warrior > Fury Warrior, Rogue",},
{["loot_id"] = "20932", ["loot_name"] = "Qiraji Bindings of Dominance", ["prio"] = "(Shoulders & Feet) Shaman > Warlock, Mage",},
{["loot_id"] = "20888", ["loot_name"] = "Qiraji Ceremonial Ring", ["prio"] = "(Ring Honored) Warlock > Rest",},
{["loot_id"] = "21602", ["loot_name"] = "Qiraji Execution Bracers", ["prio"] = "Feral > Rogue",},
{["loot_id"] = "20884", ["loot_name"] = "Qiraji Magisterial Ring", ["prio"] = "(Ring Honored) Mage, Fury Warrior, Enhance > Druid",},
{["loot_id"] = "20885", ["loot_name"] = "Qiraji Martial Drape", ["prio"] = "(Cloak Revered) Prot Warrior, Rogue > Mage, Priest",},
{["loot_id"] = "20890", ["loot_name"] = "Qiraji Ornate Hilt", ["prio"] = "(Weapons Exalted) Priest > Mage, Warlock > Druid",},
{["loot_id"] = "20889", ["loot_name"] = "Qiraji Regal Drape", ["prio"] = "(Cloak Revered) Hunter > All",},
{["loot_id"] = "20886", ["loot_name"] = "Qiraji Spiked Hilt", ["prio"] = "(Weapons Exalted) Shaman > Hunter, Warrior > Dagger Rogue",},
{["loot_id"] = "18821", ["loot_name"] = "Quick Strike Ring", ["prio"] = "Melee > Tanks",},
{["loot_id"] = "21489", ["loot_name"] = "Quicksand Waders", ["prio"] = "None",},
{["loot_id"] = "21648", ["loot_name"] = "Recomposed Boots", ["prio"] = "Soakers",},
{["loot_id"] = "19348", ["loot_name"] = "Red Dragonscale Protector", ["prio"] = "Resto Shaman",},
{["loot_id"] = "21609", ["loot_name"] = "Regenerating Belt of Vek'nilash", ["prio"] = "Resto Druid",},
{["loot_id"] = "19395", ["loot_name"] = "Rejuvenating Gem", ["prio"] = "Healers > Flask Set",},
{["loot_id"] = "23547", ["loot_name"] = "Resilience of the Scourge", ["prio"] = "Healers",},
{["loot_id"] = "22983", ["loot_name"] = "Rime Covered Mantle", ["prio"] = "Mage, Shadow Priest > Warlock",},
{["loot_id"] = "19397", ["loot_name"] = "Ring of Blackrock", ["prio"] = "Anyone",},
{["loot_id"] = "21601", ["loot_name"] = "Ring of Emperor Vek'lor", ["prio"] = "Tanks",},
{["loot_id"] = "19147", ["loot_name"] = "Ring of Spell Power", ["prio"] = "DPS > Healers",},
{["loot_id"] = "23037", ["loot_name"] = "Ring of Spiritual Fervor", ["prio"] = "Healers",},
{["loot_id"] = "21707", ["loot_name"] = "Ring of Swarming Thought", ["prio"] = "DPS",},
{["loot_id"] = "21681", ["loot_name"] = "Ring of the Devoured", ["prio"] = "None",},
{["loot_id"] = "21596", ["loot_name"] = "Ring of the Godslayer", ["prio"] = "Hunter",},
{["loot_id"] = "21620", ["loot_name"] = "Ring of the Martyr", ["prio"] = "Healers",},
{["loot_id"] = "21677", ["loot_name"] = "Ring of the Qiraji Fury", ["prio"] = "Fury Warrior",},
{["loot_id"] = "19438", ["loot_name"] = "Ringo's Blizzard Boots", ["prio"] = "Frost Mage",},
{["loot_id"] = "21836", ["loot_name"] = "Ritssyn's Ring of Chaos", ["prio"] = "Mage",},
{["loot_id"] = "19145", ["loot_name"] = "Robe of Volatile Power", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "21671", ["loot_name"] = "Robes of the Battleguard", ["prio"] = "None",},
{["loot_id"] = "21663", ["loot_name"] = "Robes of the Guardian Saint", ["prio"] = "Single-target Shaman, Resto Druid > Chain Heal Shaman, Heal Priest",},
{["loot_id"] = "21696", ["loot_name"] = "Robes of the Triumvirate", ["prio"] = "Soakers",},
{["loot_id"] = "21598", ["loot_name"] = "Royal Qiraji Belt", ["prio"] = "Prot Warrior",},
{["loot_id"] = "21597", ["loot_name"] = "Royal Scepter of Vek'lor", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "19144", ["loot_name"] = "Sabatons of the Flamewalker", ["prio"] = "Hunter, Enhance",},
{["loot_id"] = "23023", ["loot_name"] = "Sadist's Collar", ["prio"] = "None",},
{["loot_id"] = "18875", ["loot_name"] = "Salamander Scale Pants", ["prio"] = "Resto Shaman, Resto Druid",},
{["loot_id"] = "21456", ["loot_name"] = "Sandstorm Cloak", ["prio"] = "Tanks",},
{["loot_id"] = "23049", ["loot_name"] = "Sapphiron's Left Eye", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "23048", ["loot_name"] = "Sapphiron's Right Eye", ["prio"] = "Heal Priest, Resto Druid",},
{["loot_id"] = "18809", ["loot_name"] = "Sash of Whispered Secrets", ["prio"] = "Warlock, Shadow Priest",},
{["loot_id"] = "21666", ["loot_name"] = "Satura's Might", ["prio"] = "Healers w/o Staff",},
{["loot_id"] = "21668", ["loot_name"] = "Scaled Leggings of Qiraji Fury", ["prio"] = "None",},
{["loot_id"] = "21651", ["loot_name"] = "Scaled Sand Reaver Leggings", ["prio"] = "Enhance",},
{["loot_id"] = "21625", ["loot_name"] = "Scarab Brooch", ["prio"] = "Tank Healers",},
{["loot_id"] = "21839", ["loot_name"] = "Scepter of the False Prophet", ["prio"] = "Healers",},
{["loot_id"] = "23025", ["loot_name"] = "Seal of the Damned", ["prio"] = "Warlock > Mage",},
{["loot_id"] = "22815", ["loot_name"] = "Severance", ["prio"] = "None",},
{["loot_id"] = "19355", ["loot_name"] = "Shadow Wing Focus Staff", ["prio"] = "Caster DPS, Resto Druid > Rest",},
{["loot_id"] = "17074", ["loot_name"] = "Shadowstrike", ["prio"] = "Vendor Strike",},
{["loot_id"] = "21891", ["loot_name"] = "Shard of the Fallen Star", ["prio"] = "Anyone",},
{["loot_id"] = "17082", ["loot_name"] = "Shard of the Flame", ["prio"] = "DE",},
{["loot_id"] = "21622", ["loot_name"] = "Sharpened Silithid Femur", ["prio"] = "Mage, Warlock (w/o staff)",},
{["loot_id"] = "22819", ["loot_name"] = "Shield of Condemnation", ["prio"] = "Resto Shaman",},
{["loot_id"] = "19391", ["loot_name"] = "Shimmering Geta", ["prio"] = "Healers",},
{["loot_id"] = "23045", ["loot_name"] = "Shroud of Dominion", ["prio"] = "Melee, Hunter, Enhance",},
{["loot_id"] = "23018", ["loot_name"] = "Signet of the Fallen Defender", ["prio"] = "Feral",},
{["loot_id"] = "21652", ["loot_name"] = "Silithid Carapace Chestguard", ["prio"] = "Prot Warrior",},
{["loot_id"] = "21673", ["loot_name"] = "Silithid Claw", ["prio"] = "None",},
{["loot_id"] = "20931", ["loot_name"] = "Skin of the Great Sandworm", ["prio"] = "(Legs) Resto Shaman > Feral > Warlock, Hunter",},
{["loot_id"] = "23041", ["loot_name"] = "Slayer's Crest", ["prio"] = "Melee, Hunter",},
{["loot_id"] = "21626", ["loot_name"] = "Slime-coated Leggings", ["prio"] = "Soakers",},
{["loot_id"] = "18878", ["loot_name"] = "Sorcerous Dagger", ["prio"] = "Caster DPS, Healers",},
{["loot_id"] = "22799", ["loot_name"] = "Soulseeker", ["prio"] = "Warlock, Mage",},
{["loot_id"] = "22811", ["loot_name"] = "Soulstring", ["prio"] = "Hunter w/o BWL Crossbow (like Ganggang) > Melee",},
{["loot_id"] = "21494", ["loot_name"] = "Southwind's Grasp", ["prio"] = "None",},
{["loot_id"] = "19335", ["loot_name"] = "SpineShatter", ["prio"] = "Prot Warrior",},
{["loot_id"] = "22801", ["loot_name"] = "Spire of Twilight", ["prio"] = "2H Healers",},
{["loot_id"] = "18842", ["loot_name"] = "Staff of Dominance", ["prio"] = "Mage, Warlock > Healers",},
{["loot_id"] = "21128", ["loot_name"] = "Staff of the Qiraji Prophets", ["prio"] = "Warlock, Bad Mages",},
{["loot_id"] = "19356", ["loot_name"] = "Staff of the Shadow Flame", ["prio"] = "Mage, Warlock > Resto Druid, Shadow Priest",},
{["loot_id"] = "23053", ["loot_name"] = "Stormrage's Talisman of Seething", ["prio"] = "Melee, Hunter",},
{["loot_id"] = "17069", ["loot_name"] = "Striker's Mark", ["prio"] = "Rogue, Fury Warrior > Hunter, Prot Warrior",},
{["loot_id"] = "19431", ["loot_name"] = "Styleen's Impeding Scarab", ["prio"] = "Prot Warrior",},
{["loot_id"] = "18820", ["loot_name"] = "Talisman of Ephemeral Power", ["prio"] = "Mage, Warlock, Shadow Priest",},
{["loot_id"] = "19396", ["loot_name"] = "Taut Dragonhide Belt", ["prio"] = "Feral",},
{["loot_id"] = "19390", ["loot_name"] = "Taut Dragonhide Gloves", ["prio"] = "DE",},
{["loot_id"] = "19389", ["loot_name"] = "Taut Dragonhide Shoulderpads", ["prio"] = "Feral",},
{["loot_id"] = "21694", ["loot_name"] = "Ternary Mantle", ["prio"] = "Heal Priest > Resto Druid",},
{["loot_id"] = "22808", ["loot_name"] = "The Castigator", ["prio"] = "None",},
{["loot_id"] = "22988", ["loot_name"] = "The End of Dreams", ["prio"] = "Shadow Priest",},
{["loot_id"] = "23039", ["loot_name"] = "The Eye of Nerub", ["prio"] = "Hunter",},
{["loot_id"] = "23043", ["loot_name"] = "The Face of Death", ["prio"] = "Prot Warrior",},
{["loot_id"] = "23577", ["loot_name"] = "The Hungering Cold", ["prio"] = "Voxxtelum",},
{["loot_id"] = "22520", ["loot_name"] = "The Phylactery of Kel'Thuzad", ["prio"] = "Shadow Priest > DPS Roll",},
{["loot_id"] = "22818", ["loot_name"] = "The Plague Bearer", ["prio"] = "Prot Warrior",},
{["loot_id"] = "23046", ["loot_name"] = "The Restrained Essence of Sapphiron", ["prio"] = "Warlock, Mage, Shadow Priest",},
{["loot_id"] = "23021", ["loot_name"] = "The Soul Harvester's Bindings", ["prio"] = "Mage",},
{["loot_id"] = "19334", ["loot_name"] = "The Untamed Blade", ["prio"] = "2H Fury Warrior > Prot Warrior",},
{["loot_id"] = "19380", ["loot_name"] = "Therazane's Link", ["prio"] = "Enhance, Hunter > Warrior",},
{["loot_id"] = "21675", ["loot_name"] = "Thick Qirajihide Belt", ["prio"] = "None",},
{["loot_id"] = "22935", ["loot_name"] = "Touch of Frost", ["prio"] = "Frost Resist",},
{["loot_id"] = "21501", ["loot_name"] = "Toughened Silithid Hide Gloves", ["prio"] = "None",},
{["loot_id"] = "22810", ["loot_name"] = "Toxin Injector", ["prio"] = "None",},
{["loot_id"] = "21692", ["loot_name"] = "Triad Girdle", ["prio"] = "Anyone",},
{["loot_id"] = "21687", ["loot_name"] = "Ukko's Ring of Darkness", ["prio"] = "Twin Emps Warlock Tank",},
{["loot_id"] = "18547", ["loot_name"] = "Unmelting Ice Girdle", ["prio"] = "Frost Resist",},
{["loot_id"] = "21579", ["loot_name"] = "Vanquished Tentacle of C'Thun", ["prio"] = "Anyone",},
{["loot_id"] = "23017", ["loot_name"] = "Veil of the Eclipse", ["prio"] = "None",},
{["loot_id"] = "21599", ["loot_name"] = "Vek'lor's Gloves of Devastation", ["prio"] = "Enhance",},
{["loot_id"] = "20926", ["loot_name"] = "Vek'nilash's Circlet", ["prio"] = "(Helmet) Prot Warrior > Cloth Boys (NO Mish'undere)",},
{["loot_id"] = "20930", ["loot_name"] = "Vek�lor�s Diadem", ["prio"] = "(Helmet) Resto Shaman > Rogue",},
{["loot_id"] = "21680", ["loot_name"] = "Vest of Swift Execution", ["prio"] = "Feral > Enhance",},
{["loot_id"] = "21499", ["loot_name"] = "Vestments of the Shifting Sands", ["prio"] = "Heal Priest",},
{["loot_id"] = "22820", ["loot_name"] = "Wand of Fates", ["prio"] = "Warlock > Mage, Shadow Priest",},
{["loot_id"] = "21603", ["loot_name"] = "Wand of Qiraji Nobility", ["prio"] = "Warlock, Shadow Priest > Mage",},
{["loot_id"] = "23009", ["loot_name"] = "Wand of the Whispering Dead", ["prio"] = "Heal Priest",},
{["loot_id"] = "23027", ["loot_name"] = "Warmth of Forgiveness", ["prio"] = "None",},
{["loot_id"] = "21617", ["loot_name"] = "Wasphide Gauntlets", ["prio"] = "Resto Druid > Mage",},
{["loot_id"] = "22806", ["loot_name"] = "Widow's Remorse", ["prio"] = "Fury-Prot, Sword Rogue > Fury Warrior",},
{["loot_id"] = "18810", ["loot_name"] = "Wild Growth Spaulders", ["prio"] = "Resto Shaman, Resto Druid",},
{["loot_id"] = "22807", ["loot_name"] = "Wraith Blade", ["prio"] = "Mage, Warlock",},
{["loot_id"] = "19146", ["loot_name"] = "Wristguards of Stability", ["prio"] = "Feral, Fury Warrior",},
{["loot_id"] = "18812", ["loot_name"] = "Wristguards of True Flight", ["prio"] = "Prot Warrior, Hunter, Enhance",},
{["loot_id"] = "22936", ["loot_name"] = "Wristguards of Vengeance", ["prio"] = "Fury Warrior > Prot Warrior",},
}