{["loot_id"] = "32521", ["loot_name"] = "Faceplate of the Impenetrable", ["prio"] = "Dominoctus, Fug",},
{["loot_id"] = "30007", ["loot_name"] = "The Darkener's Grasp", ["prio"] = "Dominoctus",},
{["loot_id"] = "31101", ["loot_name"] = "Pauldrons of the Forgotten Conqueror", ["prio"] = "Dominoctus",},
{["loot_id"] = "6384", ["loot_name"] = "Stylish Blue Shirt", ["prio"] = "Dominoctus",},
{["loot_id"] = "31089", ["loot_name"] = "Chestguard of the Forgotten Conqueror", ["prio"] = "Dominoctus",},
{["loot_id"] = "32342", ["loot_name"] = "Girdle of Mighty Resolve", ["prio"] = "Dominoctus",},
{["loot_id"] = "31098", ["loot_name"] = "Leggings of the Forgotten Conqueror", ["prio"] = "Dominoctus",},
{["loot_id"] = "32245", ["loot_name"] = "Tide-Stomper's Greaves", ["prio"] = "Dominoctus",},
{["loot_id"] = "32279", ["loot_name"] = "The Seeker's Wristguards", ["prio"] = "Dominoctus",},
{["loot_id"] = "31092", ["loot_name"] = "Gloves of the Forgotten Conqueror", ["prio"] = "Dominoctus",},
{["loot_id"] = "30028", ["loot_name"] = "Seventh Ring of the Tirisfalen", ["prio"] = "Dominoctus",},
{["loot_id"] = "29297", ["loot_name"] = "Band of the Eternal Defender", ["prio"] = "Dominoctus, Fug",},
{["loot_id"] = "28789", ["loot_name"] = "Eye of Magtheridon", ["prio"] = "Dominoctus",},
{["loot_id"] = "29370", ["loot_name"] = "Icon of the Silver Crescent", ["prio"] = "Dominoctus",},
{["loot_id"] = "29925", ["loot_name"] = "Phoenix-Wing Cloak", ["prio"] = "Dominoctus",},
{["loot_id"] = "30910", ["loot_name"] = "Tempest of Chaos", ["prio"] = "Dominoctus",},
{["loot_id"] = "32375", ["loot_name"] = "Bulwark of Azzinoth", ["prio"] = "Dominoctus, Fug",},
{["loot_id"] = "32368", ["loot_name"] = "Tome of the Lightbringer", ["prio"] = "Dominoctus",},
{["loot_id"] = "31405", ["loot_name"] = "Purple Trophy Tabard of the Illidari", ["prio"] = "Dominoctus",},
{["loot_id"] = "32362", ["loot_name"] = "Pendant of Titans", ["prio"] = "Fug",},
{["loot_id"] = "31103", ["loot_name"] = "Pauldrons of the Forgotten Protector", ["prio"] = "Fug",},
{["loot_id"] = "31091", ["loot_name"] = "Chestguard of the Forgotten Protector", ["prio"] = "Fug",},
{["loot_id"] = "32333", ["loot_name"] = "Girdle of Stability", ["prio"] = "Fug",},
{["loot_id"] = "31100", ["loot_name"] = "Leggings of the Forgotten Protector", ["prio"] = "Fug",},
{["loot_id"] = "32268", ["loot_name"] = "Myrmidon's Treads", ["prio"] = "Fug",},
{["loot_id"] = "32232", ["loot_name"] = "Eternium Shell Bracers", ["prio"] = "Fug",},
{["loot_id"] = "32280", ["loot_name"] = "Gauntlets of Enforcement", ["prio"] = "Fug",},
{["loot_id"] = "32261", ["loot_name"] = "Band of the Abyssal Lord", ["prio"] = "Fug",},
{["loot_id"] = "31858", ["loot_name"] = "Darkmoon Card: Vengeance", ["prio"] = "Fug",},
{["loot_id"] = "31859", ["loot_name"] = "Darkmoon Card: Madness", ["prio"] = "Fug",},
{["loot_id"] = "34010", ["loot_name"] = "Pepe's Shroud of Pacification", ["prio"] = "Fug",},
{["loot_id"] = "32254", ["loot_name"] = "The Brutalizer", ["prio"] = "Fug",},
{["loot_id"] = "32253", ["loot_name"] = "Legionkiller", ["prio"] = "Fug",},
