Loading_bis_table = {
{["loot_id"] = "31003", ["loot_name"] = "Gronnstalker's Helmet", ["prio"] = "Ganggang",},
{["loot_id"] = "30017", ["loot_name"] = "Telonicus' Pendant of Mayhem", ["prio"] = "Ganggang",},
{["loot_id"] = "31006", ["loot_name"] = "Gronnstalker's Spaulders", ["prio"] = "Ganggang, Dtm, HC",},
{["loot_id"] = "4335", ["loot_name"] = "Rich Purple Silk Shirt", ["prio"] = "Ganggang",},
{["loot_id"] = "31004", ["loot_name"] = "Gronnstalker's Chestguard", ["prio"] = "Ganggang, Dtm, HC",},
{["loot_id"] = "30040", ["loot_name"] = "Belt of Deep Shadow", ["prio"] = "Ganggang",},
{["loot_id"] = "30900", ["loot_name"] = "Bow-Stitched Leggings", ["prio"] = "Ganggang",},
{["loot_id"] = "32366", ["loot_name"] = "Shadowmaster's Boots", ["prio"] = "Ganggang, Dtm, Taghan, HC",},
{["loot_id"] = "32324", ["loot_name"] = "Insidious Bands", ["prio"] = "Ganggang, Dtm, Taghan, HC",},
{["loot_id"] = "31001", ["loot_name"] = "Gronnstalker's Gloves", ["prio"] = "Ganggang, Dtm, HC",},
{["loot_id"] = "33496", ["loot_name"] = "Signet of Primal Wrath", ["prio"] = "Ganggang, Berggen, Buckkethead, Dtm, Taghan, HC",},
{["loot_id"] = "29301", ["loot_name"] = "Band of the Eternal Champion", ["prio"] = "Ganggang",},
{["loot_id"] = "32505", ["loot_name"] = "Madness of the Betrayer", ["prio"] = "Ganggang, Berggen, Buckkethead",},
{["loot_id"] = "28830", ["loot_name"] = "Dragonspine Trophy", ["prio"] = "Ganggang, Berggen, Buckkethead, Dtm, Taghan, HC",},
{["loot_id"] = "29994", ["loot_name"] = "Thalassian Wildercloak", ["prio"] = "Ganggang",},
{["loot_id"] = "33389", ["loot_name"] = "Dagger of Bad Mojo", ["prio"] = "Ganggang, Ganggang, Dtm, Dtm, HC, HC",},
{["loot_id"] = "30906", ["loot_name"] = "Bristleblitz Striker", ["prio"] = "Ganggang, Dtm, HC",},
{["loot_id"] = "28788", ["loot_name"] = "Tabard of the Protector", ["prio"] = "Ganggang, Xoen",},
{["loot_id"] = "31051", ["loot_name"] = "Hood of the Malefic", ["prio"] = "Kazlocked, Othercyde, Ularok",},
{["loot_id"] = "33281", ["loot_name"] = "Brooch of Nature's Mercy", ["prio"] = "Kazlocked, Perly, Youngsice, Amrita, Zanadune",},
{["loot_id"] = "31054", ["loot_name"] = "Mantle of the Malefic", ["prio"] = "Kazlocked, Othercyde, Ularok",},
{["loot_id"] = "30107", ["loot_name"] = "Vestments of the Sea-Witch", ["prio"] = "Kazlocked, Ularok",},
{["loot_id"] = "30888", ["loot_name"] = "Anetheron's Noose", ["prio"] = "Kazlocked, Youngsice, Ularok, Piyopiyo, Xoen, Deyat",},
{["loot_id"] = "31053", ["loot_name"] = "Leggings of the Malefic", ["prio"] = "Kazlocked, Ularok",},
{["loot_id"] = "32239", ["loot_name"] = "Slippers of the Seacaller", ["prio"] = "Kazlocked, Othercyde, Youngsice, Ularok, Stormish, Piyopiyo, Penguin, Xoen, Deyat",},
{["loot_id"] = "32586", ["loot_name"] = "Bracers of Nimble Thought", ["prio"] = "Kazlocked, Othercyde, Ularok, Stormish, Piyopiyo, Penguin, storemount",},
{["loot_id"] = "31050", ["loot_name"] = "Gloves of the Malefic", ["prio"] = "Kazlocked, Othercyde, Ularok",},
{["loot_id"] = "33497", ["loot_name"] = "Mana Attuned Band", ["prio"] = "Kazlocked, Othercyde, Ularok, storemount",},
{["loot_id"] = "32527", ["loot_name"] = "Ring of Ancient Knowledge", ["prio"] = "Kazlocked, Othercyde, Youngsice, Ularok, Stormish, Stormish, Piyopiyo, Penguin, Xoen, Deyat, storemount",},
{["loot_id"] = "32483", ["loot_name"] = "The Skull of Gul'dan", ["prio"] = "Kazlocked, Othercyde, Youngsice, Ularok, Stormish, Piyopiyo, Penguin, Xoen, Deyat",},
{["loot_id"] = "33829", ["loot_name"] = "Hex Shrunken Head", ["prio"] = "Kazlocked, Othercyde, Youngsice, Ularok, Piyopiyo, Dominoctus, Xoen, Deyat, storemount",},
{["loot_id"] = "32331", ["loot_name"] = "Cloak of the Illidari Council", ["prio"] = "Kazlocked, Ularok, Stormish, Piyopiyo, Penguin, Xoen, Deyat",},
{["loot_id"] = "30910", ["loot_name"] = "Tempest of Chaos", ["prio"] = "Kazlocked, Othercyde, Youngsice, Dominoctus, Xoen, Deyat",},
{["loot_id"] = "30872", ["loot_name"] = "Chronicle of Dark Secrets", ["prio"] = "Kazlocked, Othercyde, Youngsice, Xoen, Deyat",},
{["loot_id"] = "33192", ["loot_name"] = "Carved Witch Doctor's Stick", ["prio"] = "Kazlocked, Othercyde, Youngsice, Ularok, Xoen, Deyat, storemount",},
{["loot_id"] = "32235", ["loot_name"] = "Cursed Vision of Sargeras", ["prio"] = "Berggen, Buckkethead, Dtm, Taghan, HC",},
{["loot_id"] = "32591", ["loot_name"] = "Choker of Serrated Blades", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "30979", ["loot_name"] = "Onslaught Shoulderblades", ["prio"] = "Berggen, Buckkethead, Fug2",},
{["loot_id"] = "5107", ["loot_name"] = "Deckhand's Shirt", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "30975", ["loot_name"] = "Onslaught Breastplate", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "30032", ["loot_name"] = "Red Belt of Battle", ["prio"] = "Berggen",},
{["loot_id"] = "32341", ["loot_name"] = "Leggings of Divine Retribution", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "32345", ["loot_name"] = "Dreadboots of the Legion", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "30863", ["loot_name"] = "Deadly Cuffs", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "32278", ["loot_name"] = "Grips of Silent Justice", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "32497", ["loot_name"] = "Stormrage Signet Ring", ["prio"] = "Berggen, Buckkethead, Dtm, Taghan, HC",},
{["loot_id"] = "32323", ["loot_name"] = "Shadowmoon Destroyer's Drape", ["prio"] = "Berggen, Buckkethead, Dtm, Taghan, HC",},
{["loot_id"] = "28439", ["loot_name"] = "Dragonstrike", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "30901", ["loot_name"] = "Boundless Agony", ["prio"] = "Berggen",},
{["loot_id"] = "33474", ["loot_name"] = "Ancient Amani Longbow", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "31012", ["loot_name"] = "Skyshatter Helmet", ["prio"] = "Perly",},
{["loot_id"] = "31022", ["loot_name"] = "Skyshatter Shoulderpads", ["prio"] = "Perly",},
{["loot_id"] = "31016", ["loot_name"] = "Skyshatter Chestguard", ["prio"] = "Perly",},
{["loot_id"] = "32258", ["loot_name"] = "Naturalist's Preserving Cinch", ["prio"] = "Perly",},
{["loot_id"] = "31019", ["loot_name"] = "Skyshatter Leggings", ["prio"] = "Perly",},
{["loot_id"] = "33324", ["loot_name"] = "Treads of the Life Path", ["prio"] = "Perly, OrangeSqueez",},
{["loot_id"] = "32577", ["loot_name"] = "Living Earth Bindings", ["prio"] = "Perly",},
{["loot_id"] = "32328", ["loot_name"] = "Botanist's Gloves of Growth", ["prio"] = "Perly, Sliverlight",},
{["loot_id"] = "32528", ["loot_name"] = "Blessed Band of Karabor", ["prio"] = "Perly, Perly, OrangeSqueez, OrangeSqueez, Amrita, Amrita, Hemp, Hemp, Zanadune, Zanadune, Sliverlight",},
{["loot_id"] = "32496", ["loot_name"] = "Memento of Tyrande", ["prio"] = "Perly, OrangeSqueez, Amrita, Hemp, Zanadune, Sliverlight",},
{["loot_id"] = "29376", ["loot_name"] = "Essence of the Martyr", ["prio"] = "Perly, OrangeSqueez, Amrita, Hemp",},
{["loot_id"] = "32524", ["loot_name"] = "Shroud of the Highborne", ["prio"] = "Perly, OrangeSqueez, Amrita, Zanadune, Sliverlight",},
{["loot_id"] = "32500", ["loot_name"] = "Crystal Spire of Karabor", ["prio"] = "Perly, OrangeSqueez, Amrita, Hemp, Zanadune, Sliverlight",},
{["loot_id"] = "30882", ["loot_name"] = "Bastion of Light", ["prio"] = "Perly",},
{["loot_id"] = "28523", ["loot_name"] = "Totem of Healing Rains", ["prio"] = "Perly",},
{["loot_id"] = "31039", ["loot_name"] = "Thunderheart Cover", ["prio"] = "Furballz",},
{["loot_id"] = "33923", ["loot_name"] = "Vindicator's Pendant of Triumph", ["prio"] = "Furballz",},
{["loot_id"] = "31048", ["loot_name"] = "Thunderheart Pauldrons", ["prio"] = "Furballz",},
{["loot_id"] = "31042", ["loot_name"] = "Thunderheart Chestguard", ["prio"] = "Furballz",},
{["loot_id"] = "30106", ["loot_name"] = "Belt of One-Hundred Deaths", ["prio"] = "Furballz, Buckkethead, Taghan",},
{["loot_id"] = "31044", ["loot_name"] = "Thunderheart Leggings", ["prio"] = "Furballz",},
{["loot_id"] = "32593", ["loot_name"] = "Treads of the Den Mother", ["prio"] = "Furballz",},
{["loot_id"] = "33881", ["loot_name"] = "Vindicator's Dragonhide Bracers", ["prio"] = "Furballz",},
{["loot_id"] = "31034", ["loot_name"] = "Thunderheart Gauntlets", ["prio"] = "Furballz",},
{["loot_id"] = "29279", ["loot_name"] = "Violet Signet of the Great Protector", ["prio"] = "Furballz",},
{["loot_id"] = "32266", ["loot_name"] = "Ring of Deceitful Intent", ["prio"] = "Furballz",},
{["loot_id"] = "32658", ["loot_name"] = "Badge of Tenacity", ["prio"] = "Furballz",},
{["loot_id"] = "30627", ["loot_name"] = "Tsunami Talisman", ["prio"] = "Furballz",},
{["loot_id"] = "28660", ["loot_name"] = "Gilded Thorium Cloak", ["prio"] = "Furballz",},
{["loot_id"] = "30883", ["loot_name"] = "Pillar of Ferocity", ["prio"] = "Furballz",},
{["loot_id"] = "32387", ["loot_name"] = "Idol of the Raven Goddess", ["prio"] = "Furballz",},
{["loot_id"] = "33466", ["loot_name"] = "Loop of Cursed Bones", ["prio"] = "Othercyde, Ularok, storemount",},
{["loot_id"] = "31052", ["loot_name"] = "Robe of the Malefic", ["prio"] = "Othercyde",},
{["loot_id"] = "32256", ["loot_name"] = "Waistwrap of Infinity", ["prio"] = "Othercyde, storemount",},
{["loot_id"] = "30916", ["loot_name"] = "Leggings of Channeled Elements", ["prio"] = "Othercyde, storemount",},
{["loot_id"] = "33591", ["loot_name"] = "Shadowcaster's Drape", ["prio"] = "Othercyde, Youngsice",},
{["loot_id"] = "32236", ["loot_name"] = "Rising Tide", ["prio"] = "Buckkethead",},
{["loot_id"] = "32260", ["loot_name"] = "Choker of Endless Nightmares", ["prio"] = "Dtm, Taghan, HC",},
{["loot_id"] = "32346", ["loot_name"] = "Boneweave Girdle", ["prio"] = "Dtm, HC",},
{["loot_id"] = "31005", ["loot_name"] = "Gronnstalker's Leggings", ["prio"] = "Dtm, HC",},
{["loot_id"] = "33831", ["loot_name"] = "Berserker's Call", ["prio"] = "Dtm, Taghan, HC",},
{["loot_id"] = "30206", ["loot_name"] = "Cowl of Tirisfal", ["prio"] = "Youngsice, Xoen, Deyat",},
{["loot_id"] = "30210", ["loot_name"] = "Mantle of Tirisfal", ["prio"] = "Youngsice, Xoen, Deyat",},
{["loot_id"] = "11840", ["loot_name"] = "Master Builder's Shirt", ["prio"] = "Youngsice, Hemp",},
{["loot_id"] = "30196", ["loot_name"] = "Robes of Tirisfal", ["prio"] = "Youngsice, Xoen, Deyat",},
{["loot_id"] = "31058", ["loot_name"] = "Leggings of the Tempest", ["prio"] = "Youngsice, Piyopiyo, Xoen, Deyat",},
{["loot_id"] = "30870", ["loot_name"] = "Cuffs of Devastation", ["prio"] = "Youngsice, Xoen, Deyat",},
{["loot_id"] = "30205", ["loot_name"] = "Gloves of Tirisfal", ["prio"] = "Youngsice, Xoen, Deyat",},
{["loot_id"] = "29305", ["loot_name"] = "Band of the Eternal Sage", ["prio"] = "Youngsice, Piyopiyo, Penguin, Xoen, Deyat",},
{["loot_id"] = "31780", ["loot_name"] = "Scryers Tabard", ["prio"] = "Youngsice",},
{["loot_id"] = "32374", ["loot_name"] = "Zhar'doom, Greatstaff of the Devourer", ["prio"] = "Ularok, Stormish, Piyopiyo, Penguin, storemount",},
{["loot_id"] = "31030", ["loot_name"] = "Slayer's Shoulderpads", ["prio"] = "Taghan",},
{["loot_id"] = "31028", ["loot_name"] = "Slayer's Chestguard", ["prio"] = "Taghan",},
{["loot_id"] = "31029", ["loot_name"] = "Slayer's Legguards", ["prio"] = "Taghan",},
{["loot_id"] = "31026", ["loot_name"] = "Slayer's Handguards", ["prio"] = "Taghan",},
{["loot_id"] = "30082", ["loot_name"] = "Talon of Azshara", ["prio"] = "Taghan",},
{["loot_id"] = "32369", ["loot_name"] = "Blade of Savagery", ["prio"] = "Taghan",},
{["loot_id"] = "29949", ["loot_name"] = "Arcanite Steam-Pistol", ["prio"] = "Taghan",},
{["loot_id"] = "31014", ["loot_name"] = "Skyshatter Headguard", ["prio"] = "Stormish, Penguin",},
{["loot_id"] = "32349", ["loot_name"] = "Translucent Spellthread Necklace", ["prio"] = "Stormish",},
{["loot_id"] = "31023", ["loot_name"] = "Skyshatter Mantle", ["prio"] = "Stormish, Penguin",},
{["loot_id"] = "31017", ["loot_name"] = "Skyshatter Breastplate", ["prio"] = "Stormish, Penguin",},
{["loot_id"] = "32276", ["loot_name"] = "Flashfire Girdle", ["prio"] = "Stormish, Penguin",},
{["loot_id"] = "31020", ["loot_name"] = "Skyshatter Legguards", ["prio"] = "Stormish, Penguin",},
{["loot_id"] = "31008", ["loot_name"] = "Skyshatter Gauntlets", ["prio"] = "Stormish, Penguin",},
{["loot_id"] = "29370", ["loot_name"] = "Icon of the Silver Crescent", ["prio"] = "Stormish, Dominoctus, storemount",},
{["loot_id"] = "32330", ["loot_name"] = "Totem of Ancestral Guidance", ["prio"] = "Stormish, Penguin",},
{["loot_id"] = "32525", ["loot_name"] = "Cowl of the Illidari High Lord", ["prio"] = "Piyopiyo",},
{["loot_id"] = "32589", ["loot_name"] = "Hellfire-Encased Pendant", ["prio"] = "Piyopiyo",},
{["loot_id"] = "31059", ["loot_name"] = "Mantle of the Tempest", ["prio"] = "Piyopiyo",},
{["loot_id"] = "31057", ["loot_name"] = "Robes of the Tempest", ["prio"] = "Piyopiyo",},
{["loot_id"] = "31055", ["loot_name"] = "Gloves of the Tempest", ["prio"] = "Piyopiyo",},
{["loot_id"] = "29982", ["loot_name"] = "Wand of the Forgotten Star", ["prio"] = "Piyopiyo",},
{["loot_id"] = "30988", ["loot_name"] = "Lightbringer Greathelm", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "32370", ["loot_name"] = "Nadina's Pendant of Purity", ["prio"] = "OrangeSqueez, Hemp",},
{["loot_id"] = "30996", ["loot_name"] = "Lightbringer Pauldrons", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "30992", ["loot_name"] = "Lightbringer Chestpiece", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "30897", ["loot_name"] = "Girdle of Hope", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "30994", ["loot_name"] = "Lightbringer Leggings", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "30862", ["loot_name"] = "Blessed Adamantite Bracers", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "30112", ["loot_name"] = "Glorious Gauntlets of Crestfall", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "32255", ["loot_name"] = "Felstone Bulwark", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "25644", ["loot_name"] = "Blessed Book of Nagrand", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "30015", ["loot_name"] = "The Sun King's Talisman", ["prio"] = "Penguin, Xoen, Deyat",},
{["loot_id"] = "28785", ["loot_name"] = "The Lightning Capacitor", ["prio"] = "Penguin",},
{["loot_id"] = "32521", ["loot_name"] = "Faceplate of the Impenetrable", ["prio"] = "Dominoctus, Fug2",},
{["loot_id"] = "30007", ["loot_name"] = "The Darkener's Grasp", ["prio"] = "Dominoctus",},
{["loot_id"] = "30998", ["loot_name"] = "Lightbringer Shoulderguards", ["prio"] = "Dominoctus",},
{["loot_id"] = "30991", ["loot_name"] = "Lightbringer Chestguard", ["prio"] = "Dominoctus",},
{["loot_id"] = "32342", ["loot_name"] = "Girdle of Mighty Resolve", ["prio"] = "Dominoctus",},
{["loot_id"] = "30995", ["loot_name"] = "Lightbringer Legguards", ["prio"] = "Dominoctus",},
{["loot_id"] = "32245", ["loot_name"] = "Tide-Stomper's Greaves", ["prio"] = "Dominoctus",},
{["loot_id"] = "32279", ["loot_name"] = "The Seeker's Wristguards", ["prio"] = "Dominoctus",},
{["loot_id"] = "30985", ["loot_name"] = "Lightbringer Handguards", ["prio"] = "Dominoctus",},
{["loot_id"] = "30028", ["loot_name"] = "Seventh Ring of the Tirisfalen", ["prio"] = "Dominoctus",},
{["loot_id"] = "33499", ["loot_name"] = "Signet of the Last Defender", ["prio"] = "Dominoctus",},
{["loot_id"] = "33593", ["loot_name"] = "Slikk's Cloak of Placation", ["prio"] = "Dominoctus",},
{["loot_id"] = "32375", ["loot_name"] = "Bulwark of Azzinoth", ["prio"] = "Dominoctus, Fug2",},
{["loot_id"] = "32368", ["loot_name"] = "Tome of the Lightbringer", ["prio"] = "Dominoctus",},
{["loot_id"] = "31063", ["loot_name"] = "Cowl of Absolution", ["prio"] = "Amrita, Hemp, Zanadune",},
{["loot_id"] = "31069", ["loot_name"] = "Mantle of Absolution", ["prio"] = "Amrita, Hemp",},
{["loot_id"] = "31066", ["loot_name"] = "Vestments of Absolution", ["prio"] = "Amrita, Hemp, Zanadune",},
{["loot_id"] = "30895", ["loot_name"] = "Angelista's Sash", ["prio"] = "Amrita, Hemp, Zanadune",},
{["loot_id"] = "30912", ["loot_name"] = "Leggings of Eternity", ["prio"] = "Amrita, Hemp, Zanadune, Sliverlight",},
{["loot_id"] = "32609", ["loot_name"] = "Boots of the Divine Light", ["prio"] = "Amrita, Hemp, Zanadune, Sliverlight",},
{["loot_id"] = "32584", ["loot_name"] = "Swiftheal Wraps", ["prio"] = "Amrita, Hemp, Zanadune",},
{["loot_id"] = "31060", ["loot_name"] = "Gloves of Absolution", ["prio"] = "Amrita, Hemp, Zanadune",},
{["loot_id"] = "30911", ["loot_name"] = "Scepter of Purification", ["prio"] = "Amrita, Hemp, Zanadune, Sliverlight",},
{["loot_id"] = "32363", ["loot_name"] = "Naaru-Blessed Life Rod", ["prio"] = "Amrita, Hemp, Zanadune",},
{["loot_id"] = "32362", ["loot_name"] = "Pendant of Titans", ["prio"] = "Fug2",},
{["loot_id"] = "30976", ["loot_name"] = "Onslaught Chestguard", ["prio"] = "Fug2",},
{["loot_id"] = "32333", ["loot_name"] = "Girdle of Stability", ["prio"] = "Fug2",},
{["loot_id"] = "30978", ["loot_name"] = "Onslaught Legguards", ["prio"] = "Fug2",},
{["loot_id"] = "32268", ["loot_name"] = "Myrmidon's Treads", ["prio"] = "Fug2",},
{["loot_id"] = "32232", ["loot_name"] = "Eternium Shell Bracers", ["prio"] = "Fug2",},
{["loot_id"] = "32280", ["loot_name"] = "Gauntlets of Enforcement", ["prio"] = "Fug2",},
{["loot_id"] = "29297", ["loot_name"] = "Band of the Eternal Defender", ["prio"] = "Fug2",},
{["loot_id"] = "32261", ["loot_name"] = "Band of the Abyssal Lord", ["prio"] = "Fug2",},
{["loot_id"] = "37127", ["loot_name"] = "Brightbrew Charm", ["prio"] = "Fug2",},
{["loot_id"] = "31859", ["loot_name"] = "Darkmoon Card: Madness", ["prio"] = "Fug2",},
{["loot_id"] = "34010", ["loot_name"] = "Pepe's Shroud of Pacification", ["prio"] = "Fug2",},
{["loot_id"] = "32254", ["loot_name"] = "The Brutalizer", ["prio"] = "Fug2",},
{["loot_id"] = "32253", ["loot_name"] = "Legionkiller", ["prio"] = "Fug2",},
{["loot_id"] = "32337", ["loot_name"] = "Shroud of Forgiveness", ["prio"] = "Hemp",},
{["loot_id"] = "31064", ["loot_name"] = "Hood of Absolution", ["prio"] = "storemount",},
{["loot_id"] = "31070", ["loot_name"] = "Shoulderpads of Absolution", ["prio"] = "storemount",},
{["loot_id"] = "31065", ["loot_name"] = "Shroud of Absolution", ["prio"] = "storemount",},
{["loot_id"] = "33357", ["loot_name"] = "Footpads of Madness", ["prio"] = "storemount",},
{["loot_id"] = "31061", ["loot_name"] = "Handguards of Absolution", ["prio"] = "storemount",},
{["loot_id"] = "32590", ["loot_name"] = "Nethervoid Cloak", ["prio"] = "storemount",},
{["loot_id"] = "32585", ["loot_name"] = "Swiftheal Mantle", ["prio"] = "Zanadune",},
{["loot_id"] = "38288", ["loot_name"] = "Direbrew Hops", ["prio"] = "Zanadune, Sliverlight",},
{["loot_id"] = "31037", ["loot_name"] = "Thunderheart Helmet", ["prio"] = "Sliverlight",},
{["loot_id"] = "30018", ["loot_name"] = "Lord Sanguinar's Claim", ["prio"] = "Sliverlight",},
{["loot_id"] = "31047", ["loot_name"] = "Thunderheart Spaulders", ["prio"] = "Sliverlight",},
{["loot_id"] = "31041", ["loot_name"] = "Thunderheart Tunic", ["prio"] = "Sliverlight",},
{["loot_id"] = "32339", ["loot_name"] = "Belt of Primal Majesty", ["prio"] = "Sliverlight",},
{["loot_id"] = "32582", ["loot_name"] = "Bracers of Renewed Life", ["prio"] = "Sliverlight",},
{["loot_id"] = "29309", ["loot_name"] = "Band of the Eternal Restorer", ["prio"] = "Sliverlight",},
{["loot_id"] = "27886", ["loot_name"] = "Idol of the Emerald Queen", ["prio"] = "Sliverlight",},
}
