Loading_bis_table = {
{["loot_id"] = "34333", ["loot_name"] = "Coif of Alleria", ["prio"] = "Dtm, Huntercrow, Buckkethead",},
{["loot_id"] = "34177", ["loot_name"] = "Clutch of Demise", ["prio"] = "Dtm, Huntercrow, Endai, Buckkethead, Berggen",},
{["loot_id"] = "31103", ["loot_name"] = "Pauldrons of the Forgotten Protector", ["prio"] = "Dtm, Huntercrow, Perly, Penguin, Stormish",},
{["loot_id"] = "34397", ["loot_name"] = "Bladed Chaos Tunic", ["prio"] = "Dtm, Taghan, Huntercrow, Endai, Buckkethead",},
{["loot_id"] = "34854", ["loot_name"] = "Belt of the Forgotten Protector", ["prio"] = "Dtm, Huntercrow, Perly, Endai, Penguin, Buckkethead, Berggen, Stormish",},
{["loot_id"] = "34188", ["loot_name"] = "Leggings of the Immortal Night", ["prio"] = "Dtm, Taghan, Huntercrow, Endai, Berggen",},
{["loot_id"] = "34857", ["loot_name"] = "Boots of the Forgotten Protector", ["prio"] = "Dtm, Huntercrow, Perly, Endai, Penguin, Buckkethead, Berggen, Stormish",},
{["loot_id"] = "34443", ["loot_name"] = "Gronnstalker's Bracers", ["prio"] = "Dtm, Huntercrow",},
{["loot_id"] = "34370", ["loot_name"] = "Gloves of Immortal Dusk", ["prio"] = "Dtm, Taghan, Huntercrow",},
{["loot_id"] = "34189", ["loot_name"] = "Band of Ruinous Delight", ["prio"] = "Dtm, Taghan, Huntercrow, Endai, Buckkethead, Berggen",},
{["loot_id"] = "34361", ["loot_name"] = "Hard Khorium Band", ["prio"] = "Dtm, Cheeps, Huntercrow",},
{["loot_id"] = "34427", ["loot_name"] = "Blackened Naaru Sliver", ["prio"] = "Dtm, Taghan, Huntercrow, Endai, Buckkethead, Berggen",},
{["loot_id"] = "33831", ["loot_name"] = "Berserker's Call", ["prio"] = "Dtm, Cheeps, Huntercrow",},
{["loot_id"] = "34241", ["loot_name"] = "Cloak of Unforgivable Sin", ["prio"] = "Dtm, Taghan, Cheeps, Huntercrow, Endai, Buckkethead, Berggen",},
{["loot_id"] = "34331", ["loot_name"] = "Hand of the Deceiver", ["prio"] = "Dtm, Huntercrow, Endai, Buckkethead, Berggen",},
{["loot_id"] = "34329", ["loot_name"] = "Crux of the Apocalypse", ["prio"] = "Dtm, Huntercrow",},
{["loot_id"] = "34334", ["loot_name"] = "Thori'dal, the Stars' Fury", ["prio"] = "Dtm, Huntercrow",},
{["loot_id"] = "34340", ["loot_name"] = "Dark Conjuror's Collar", ["prio"] = "Kazlocked, Ularok, sygnom, Piyopiyo",},
{["loot_id"] = "34204", ["loot_name"] = "Amulet of Unfettered Magics", ["prio"] = "Kazlocked, strwbrrynsqk, Ularok, Penguin, sygnom, Stormish, Piyopiyo, Othercyde",},
{["loot_id"] = "31101", ["loot_name"] = "Pauldrons of the Forgotten Conqueror", ["prio"] = "Kazlocked, Ularok, sygnom",},
{["loot_id"] = "34364", ["loot_name"] = "Sunfire Robe", ["prio"] = "Kazlocked, Ularok, sygnom, Piyopiyo, Othercyde",},
{["loot_id"] = "34853", ["loot_name"] = "Belt of the Forgotten Conqueror", ["prio"] = "Kazlocked, Cheeps, Dominoctus, Ularok, Amrita, sygnom, Zanadune, Hemp, Orangesqueez, Othercyde",},
{["loot_id"] = "34181", ["loot_name"] = "Leggings of Calamity", ["prio"] = "Kazlocked, Ularok, Xoen, Piyopiyo, Deyat, Othercyde",},
{["loot_id"] = "34856", ["loot_name"] = "Boots of the Forgotten Conqueror", ["prio"] = "Kazlocked, Cheeps, Dominoctus, Ularok, Amrita, sygnom, Zanadune, Hemp, Orangesqueez, Othercyde",},
{["loot_id"] = "34436", ["loot_name"] = "Bracers of the Malefic", ["prio"] = "Kazlocked, Ularok, Othercyde",},
{["loot_id"] = "34344", ["loot_name"] = "Handguards of Defiled Worlds", ["prio"] = "Kazlocked, strwbrrynsqk, Ularok, Piyopiyo, Othercyde",},
{["loot_id"] = "34362", ["loot_name"] = "Loop of Forged Power", ["prio"] = "Kazlocked, strwbrrynsqk, Ularok, Penguin, Xoen, Stormish, Piyopiyo, Othercyde",},
{["loot_id"] = "34230", ["loot_name"] = "Ring of Omnipotence", ["prio"] = "Kazlocked, strwbrrynsqk, Ularok, Penguin, sygnom, Stormish, Piyopiyo, Deyat",},
{["loot_id"] = "32483", ["loot_name"] = "The Skull of Gul'dan", ["prio"] = "Kazlocked, Ularok, Xoen, sygnom, Piyopiyo, Deyat, Othercyde",},
{["loot_id"] = "34429", ["loot_name"] = "Shifting Naaru Sliver", ["prio"] = "Kazlocked, strwbrrynsqk, Ularok, Penguin, Xoen, sygnom, Stormish, Piyopiyo",},
{["loot_id"] = "34242", ["loot_name"] = "Tattered Cape of Antonidas", ["prio"] = "Kazlocked, Dominoctus, strwbrrynsqk, Ularok, Penguin, Xoen, sygnom, Stormish, Piyopiyo, Deyat, Othercyde",},
{["loot_id"] = "34336", ["loot_name"] = "Sunflare", ["prio"] = "Kazlocked, strwbrrynsqk, Ularok, Penguin, Xoen, sygnom, Stormish, Piyopiyo, Deyat, Othercyde",},
{["loot_id"] = "34179", ["loot_name"] = "Heart of the Pit", ["prio"] = "Kazlocked, strwbrrynsqk, Ularok, Penguin, Xoen, sygnom, Stormish, Piyopiyo, Deyat, Othercyde",},
{["loot_id"] = "34347", ["loot_name"] = "Wand of the Demonsoul", ["prio"] = "Kazlocked, Ularok, Xoen, sygnom, Piyopiyo, Deyat, Othercyde",},
{["loot_id"] = "34244", ["loot_name"] = "Duplicitous Guise", ["prio"] = "Taghan, Endai",},
{["loot_id"] = "34358", ["loot_name"] = "Hard Khorium Choker", ["prio"] = "Taghan",},
{["loot_id"] = "31102", ["loot_name"] = "Pauldrons of the Forgotten Vanquisher", ["prio"] = "Taghan, Piyopiyo",},
{["loot_id"] = "34855", ["loot_name"] = "Belt of the Forgotten Vanquisher", ["prio"] = "Taghan, strwbrrynsqk, Furballz, Sliverlight, Xoen, Piyopiyo, Deyat",},
{["loot_id"] = "34858", ["loot_name"] = "Boots of the Forgotten Vanquisher", ["prio"] = "Taghan, strwbrrynsqk, Furballz, Sliverlight, Xoen, Piyopiyo, Deyat",},
{["loot_id"] = "34448", ["loot_name"] = "Slayer's Bracers", ["prio"] = "Taghan",},
{["loot_id"] = "32497", ["loot_name"] = "Stormrage Signet Ring", ["prio"] = "Taghan, Endai, Buckkethead, Berggen",},
{["loot_id"] = "28830", ["loot_name"] = "Dragonspine Trophy", ["prio"] = "Taghan, Buckkethead, Berggen",},
{["loot_id"] = "32837", ["loot_name"] = "Warglaive of Azzinoth", ["prio"] = "Taghan",},
{["loot_id"] = "32838", ["loot_name"] = "Warglaive of Azzinoth", ["prio"] = "Taghan",},
{["loot_id"] = "34196", ["loot_name"] = "Golden Bow of Quel'Thalas", ["prio"] = "Taghan",},
{["loot_id"] = "32373", ["loot_name"] = "Helm of the Illidari Shatterer", ["prio"] = "Cheeps",},
{["loot_id"] = "32260", ["loot_name"] = "Choker of Endless Nightmares", ["prio"] = "Cheeps",},
{["loot_id"] = "34388", ["loot_name"] = "Pauldrons of Berserking", ["prio"] = "Cheeps, Buckkethead, Berggen",},
{["loot_id"] = "34215", ["loot_name"] = "Warharness of Reckless Fury", ["prio"] = "Cheeps",},
{["loot_id"] = "34180", ["loot_name"] = "Felfury Legplates", ["prio"] = "Cheeps, Buckkethead",},
{["loot_id"] = "34431", ["loot_name"] = "Lightbringer Bands", ["prio"] = "Cheeps",},
{["loot_id"] = "34341", ["loot_name"] = "Borderland Paingrips", ["prio"] = "Cheeps",},
{["loot_id"] = "32335", ["loot_name"] = "Unstoppable Aggressor's Ring", ["prio"] = "Cheeps",},
{["loot_id"] = "34472", ["loot_name"] = "Shard of Contempt", ["prio"] = "Cheeps, Endai",},
{["loot_id"] = "34247", ["loot_name"] = "Apolyon, the Soul-Render", ["prio"] = "Cheeps",},
{["loot_id"] = "27484", ["loot_name"] = "Libram of Avengement", ["prio"] = "Cheeps",},
{["loot_id"] = "34401", ["loot_name"] = "Helm of Uther's Resolve", ["prio"] = "Dominoctus",},
{["loot_id"] = "34178", ["loot_name"] = "Collar of the Pit Lord", ["prio"] = "Dominoctus, Furballz",},
{["loot_id"] = "34389", ["loot_name"] = "Spaulders of the Thalassian Defender", ["prio"] = "Dominoctus",},
{["loot_id"] = "34216", ["loot_name"] = "Heroic Judicator's Chestguard", ["prio"] = "Dominoctus",},
{["loot_id"] = "34382", ["loot_name"] = "Judicator's Legguards", ["prio"] = "Dominoctus",},
{["loot_id"] = "34433", ["loot_name"] = "Lightbringer Wristguards", ["prio"] = "Dominoctus",},
{["loot_id"] = "31092", ["loot_name"] = "Gloves of the Forgotten Conqueror", ["prio"] = "Dominoctus",},
{["loot_id"] = "30028", ["loot_name"] = "Seventh Ring of the Tirisfalen", ["prio"] = "Dominoctus",},
{["loot_id"] = "34213", ["loot_name"] = "Ring of Hardened Resolve", ["prio"] = "Dominoctus, Furballz",},
{["loot_id"] = "33829", ["loot_name"] = "Hex Shrunken Head", ["prio"] = "Dominoctus, strwbrrynsqk, Penguin, Stormish, Deyat, Othercyde",},
{["loot_id"] = "31858", ["loot_name"] = "Darkmoon Card: Vengeance", ["prio"] = "Dominoctus",},
{["loot_id"] = "30910", ["loot_name"] = "Tempest of Chaos", ["prio"] = "Dominoctus",},
{["loot_id"] = "34185", ["loot_name"] = "Sword Breaker's Bulwark", ["prio"] = "Dominoctus",},
{["loot_id"] = "32368", ["loot_name"] = "Tome of the Lightbringer", ["prio"] = "Dominoctus",},
{["loot_id"] = "34403", ["loot_name"] = "Cover of Ursoc the Mighty", ["prio"] = "strwbrrynsqk",},
{["loot_id"] = "34391", ["loot_name"] = "Spaulders of Devastation", ["prio"] = "strwbrrynsqk",},
{["loot_id"] = "31090", ["loot_name"] = "Chestguard of the Forgotten Vanquisher", ["prio"] = "strwbrrynsqk",},
{["loot_id"] = "34169", ["loot_name"] = "Breeches of Natural Aggression", ["prio"] = "strwbrrynsqk",},
{["loot_id"] = "34446", ["loot_name"] = "Thunderheart Bands", ["prio"] = "strwbrrynsqk",},
{["loot_id"] = "32387", ["loot_name"] = "Idol of the Raven Goddess", ["prio"] = "strwbrrynsqk",},
{["loot_id"] = "34402", ["loot_name"] = "Shroud of Chieftain Ner'zhul", ["prio"] = "Perly",},
{["loot_id"] = "33281", ["loot_name"] = "Brooch of Nature's Mercy", ["prio"] = "Perly, Sliverlight, Xoen, Amrita, Zanadune, Deyat, Hemp",},
{["loot_id"] = "34375", ["loot_name"] = "Sun-Drenched Scale Chestguard", ["prio"] = "Perly",},
{["loot_id"] = "34383", ["loot_name"] = "Kilt of Spiritual Reconstruction", ["prio"] = "Perly, Orangesqueez",},
{["loot_id"] = "34438", ["loot_name"] = "Skyshatter Bracers", ["prio"] = "Perly",},
{["loot_id"] = "34409", ["loot_name"] = "Gauntlets of the Ancient Frostwolf", ["prio"] = "Perly",},
{["loot_id"] = "32528", ["loot_name"] = "Blessed Band of Karabor", ["prio"] = "Perly, Perly, Sliverlight, Amrita, Amrita, Zanadune, Hemp",},
{["loot_id"] = "32496", ["loot_name"] = "Memento of Tyrande", ["prio"] = "Perly, Sliverlight, Amrita, Zanadune, Hemp, Orangesqueez",},
{["loot_id"] = "34430", ["loot_name"] = "Glimmering Naaru Sliver", ["prio"] = "Perly, Zanadune, Hemp, Orangesqueez",},
{["loot_id"] = "32524", ["loot_name"] = "Shroud of the Highborne", ["prio"] = "Perly, Sliverlight, Amrita, Zanadune, Hemp",},
{["loot_id"] = "34335", ["loot_name"] = "Hammer of Sanctification", ["prio"] = "Perly, Sliverlight, Amrita, Zanadune, Hemp, Orangesqueez",},
{["loot_id"] = "34231", ["loot_name"] = "Aegis of Angelic Fortune", ["prio"] = "Perly",},
{["loot_id"] = "28523", ["loot_name"] = "Totem of Healing Rains", ["prio"] = "Perly",},
{["loot_id"] = "34404", ["loot_name"] = "Mask of the Fury Hunter", ["prio"] = "Furballz",},
{["loot_id"] = "34392", ["loot_name"] = "Demontooth Shoulderpads", ["prio"] = "Furballz, Endai",},
{["loot_id"] = "34211", ["loot_name"] = "Harness of Carnal Instinct", ["prio"] = "Furballz",},
{["loot_id"] = "34385", ["loot_name"] = "Leggings of the Immortal Beast", ["prio"] = "Furballz",},
{["loot_id"] = "34444", ["loot_name"] = "Thunderheart Wristguards", ["prio"] = "Furballz",},
{["loot_id"] = "34408", ["loot_name"] = "Gloves of the Forest Drifter", ["prio"] = "Furballz",},
{["loot_id"] = "34888", ["loot_name"] = "Ring of the Stalwart Protector", ["prio"] = "Furballz",},
{["loot_id"] = "32658", ["loot_name"] = "Badge of Tenacity", ["prio"] = "Furballz",},
{["loot_id"] = "34473", ["loot_name"] = "Commendation of Kael'thas", ["prio"] = "Furballz",},
{["loot_id"] = "34190", ["loot_name"] = "Crimson Paragon's Cover", ["prio"] = "Furballz",},
{["loot_id"] = "34198", ["loot_name"] = "Stanchion of Primal Instinct", ["prio"] = "Furballz",},
{["loot_id"] = "33509", ["loot_name"] = "Idol of Terror", ["prio"] = "Furballz",},
{["loot_id"] = "34245", ["loot_name"] = "Cover of Ursol the Wise", ["prio"] = "Sliverlight",},
{["loot_id"] = "34209", ["loot_name"] = "Spaulders of Reclamation", ["prio"] = "Sliverlight",},
{["loot_id"] = "34212", ["loot_name"] = "Sunglow Vest", ["prio"] = "Sliverlight",},
{["loot_id"] = "34384", ["loot_name"] = "Breeches of Natural Splendor", ["prio"] = "Sliverlight",},
{["loot_id"] = "34445", ["loot_name"] = "Thunderheart Bracers", ["prio"] = "Sliverlight",},
{["loot_id"] = "34367", ["loot_name"] = "Hands of Eternal Light", ["prio"] = "Sliverlight",},
{["loot_id"] = "29309", ["loot_name"] = "Band of the Eternal Restorer", ["prio"] = "Sliverlight",},
{["loot_id"] = "38288", ["loot_name"] = "Direbrew Hops", ["prio"] = "Sliverlight",},
{["loot_id"] = "34206", ["loot_name"] = "Book of Highborne Hymns", ["prio"] = "Sliverlight, Amrita, Zanadune, Hemp, Orangesqueez",},
{["loot_id"] = "27886", ["loot_name"] = "Idol of the Emerald Queen", ["prio"] = "Sliverlight",},
{["loot_id"] = "34439", ["loot_name"] = "Skyshatter Wristguards", ["prio"] = "Endai",},
{["loot_id"] = "34343", ["loot_name"] = "Thalassian Ranger Gauntlets", ["prio"] = "Endai, Buckkethead, Berggen",},
{["loot_id"] = "34346", ["loot_name"] = "Mounting Vengeance", ["prio"] = "Endai, Buckkethead, Berggen",},
{["loot_id"] = "33507", ["loot_name"] = "Stonebreaker's Totem", ["prio"] = "Endai",},
{["loot_id"] = "34332", ["loot_name"] = "Cowl of Gul'dan", ["prio"] = "Penguin, Stormish",},
{["loot_id"] = "18231", ["loot_name"] = "Sleeveless T-Shirt", ["prio"] = "Penguin",},
{["loot_id"] = "34396", ["loot_name"] = "Garments of Crashing Shores", ["prio"] = "Penguin, Stormish",},
{["loot_id"] = "34186", ["loot_name"] = "Chain Links of the Tumultuous Storm", ["prio"] = "Penguin, Stormish",},
{["loot_id"] = "34437", ["loot_name"] = "Skyshatter Bands", ["prio"] = "Penguin, Stormish",},
{["loot_id"] = "34350", ["loot_name"] = "Gauntlets of the Ancient Shadowmoon", ["prio"] = "Penguin, Stormish",},
{["loot_id"] = "32330", ["loot_name"] = "Totem of Ancestral Guidance", ["prio"] = "Penguin, Stormish",},
{["loot_id"] = "28788", ["loot_name"] = "Tabard of the Protector", ["prio"] = "Penguin, Xoen",},
{["loot_id"] = "34441", ["loot_name"] = "Onslaught Bracers", ["prio"] = "Buckkethead, Berggen",},
{["loot_id"] = "34892", ["loot_name"] = "Crossbow of Relentless Strikes", ["prio"] = "Buckkethead",},
{["loot_id"] = "30244", ["loot_name"] = "Helm of the Vanquished Hero", ["prio"] = "Xoen, Deyat",},
{["loot_id"] = "30250", ["loot_name"] = "Pauldrons of the Vanquished Hero", ["prio"] = "Xoen, Deyat",},
{["loot_id"] = "34399", ["loot_name"] = "Robes of Ghostly Hatred", ["prio"] = "Xoen, Deyat",},
{["loot_id"] = "34447", ["loot_name"] = "Bracers of the Tempest", ["prio"] = "Xoen, Piyopiyo, Deyat",},
{["loot_id"] = "34406", ["loot_name"] = "Gloves of Tyri's Power", ["prio"] = "Xoen, sygnom, Deyat",},
{["loot_id"] = "29305", ["loot_name"] = "Band of the Eternal Sage", ["prio"] = "Xoen",},
{["loot_id"] = "34345", ["loot_name"] = "Crown of Anasterian", ["prio"] = "Berggen",},
{["loot_id"] = "14617", ["loot_name"] = "Sawbones Shirt", ["prio"] = "Berggen",},
{["loot_id"] = "34377", ["loot_name"] = "Hard Khorium Battleplate", ["prio"] = "Berggen",},
{["loot_id"] = "34349", ["loot_name"] = "Blade of Life's Inevitability", ["prio"] = "Berggen",},
{["loot_id"] = "22999", ["loot_name"] = "Tabard of the Argent Dawn", ["prio"] = "Berggen",},
{["loot_id"] = "34339", ["loot_name"] = "Cowl of Light's Purity", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "34202", ["loot_name"] = "Shawl of Wonderment", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "34233", ["loot_name"] = "Robes of Faltered Light", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "34170", ["loot_name"] = "Pantaloons of Calming Strife", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "34435", ["loot_name"] = "Cuffs of Absolution", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "34342", ["loot_name"] = "Handguards of the Dawn", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "29376", ["loot_name"] = "Essence of the Martyr", ["prio"] = "Amrita",},
{["loot_id"] = "34348", ["loot_name"] = "Wand of Cleansing Light", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "34386", ["loot_name"] = "Pantaloons of Growing Strife", ["prio"] = "sygnom",},
{["loot_id"] = "34434", ["loot_name"] = "Bracers of Absolution", ["prio"] = "sygnom",},
{["loot_id"] = "32527", ["loot_name"] = "Ring of Ancient Knowledge", ["prio"] = "sygnom, Deyat",},
{["loot_id"] = "34363", ["loot_name"] = "Ring of Flowing Life", ["prio"] = "Zanadune, Hemp, Orangesqueez",},
{["loot_id"] = "4335", ["loot_name"] = "Rich Purple Silk Shirt", ["prio"] = "Stormish",},
{["loot_id"] = "34243", ["loot_name"] = "Helm of Burning Righteousness", ["prio"] = "Orangesqueez",},
{["loot_id"] = "34360", ["loot_name"] = "Amulet of Flowing Life", ["prio"] = "Orangesqueez",},
{["loot_id"] = "34193", ["loot_name"] = "Spaulders of the Thalassian Savior", ["prio"] = "Orangesqueez",},
{["loot_id"] = "34229", ["loot_name"] = "Garments of Serene Shores", ["prio"] = "Orangesqueez",},
{["loot_id"] = "34432", ["loot_name"] = "Lightbringer Bracers", ["prio"] = "Orangesqueez",},
{["loot_id"] = "34240", ["loot_name"] = "Gauntlets of the Soothed Soul", ["prio"] = "Orangesqueez",},
{["loot_id"] = "34166", ["loot_name"] = "Band of Lucent Beams", ["prio"] = "Orangesqueez",},
{["loot_id"] = "34205", ["loot_name"] = "Shroud of Redeemed Souls", ["prio"] = "Orangesqueez",},
{["loot_id"] = "25644", ["loot_name"] = "Blessed Book of Nagrand", ["prio"] = "Orangesqueez",},
{["loot_id"] = "31097", ["loot_name"] = "Helm of the Forgotten Conqueror", ["prio"] = "Othercyde",},
{["loot_id"] = "34210", ["loot_name"] = "Amice of the Convoker", ["prio"] = "Othercyde",},
{["loot_id"] = "33497", ["loot_name"] = "Mana Attuned Band", ["prio"] = "Othercyde",},
}
