Loading_bis_table = {
{["loot_id"] = "31097", ["loot_name"] = "Helm of the Forgotten Conqueror", ["prio"] = "Kazlocked, Othercyde, Ularok, OrangeSqueez, Amrita, storemount, Zanadune, sygnom",},
{["loot_id"] = "33281", ["loot_name"] = "Brooch of Nature's Mercy", ["prio"] = "Kazlocked, Perly, Amrita, Zanadune, Hemp, Penguin, strwbrrynsqk",},
{["loot_id"] = "31101", ["loot_name"] = "Pauldrons of the Forgotten Conqueror", ["prio"] = "Kazlocked, Othercyde, Ularok, OrangeSqueez, Dominoctus, Amrita, storemount, Hemp, sygnom",},
{["loot_id"] = "30107", ["loot_name"] = "Vestments of the Sea-Witch", ["prio"] = "Kazlocked, Ularok",},
{["loot_id"] = "30888", ["loot_name"] = "Anetheron's Noose", ["prio"] = "Kazlocked, Ularok, Piyopiyo, Xoen, Deyat",},
{["loot_id"] = "31098", ["loot_name"] = "Leggings of the Forgotten Conqueror", ["prio"] = "Kazlocked, Ularok, OrangeSqueez, Dominoctus",},
{["loot_id"] = "32239", ["loot_name"] = "Slippers of the Seacaller", ["prio"] = "Kazlocked, Othercyde, Ularok, Stormish, Piyopiyo, Xoen, Deyat, Penguin, strwbrrynsqk",},
{["loot_id"] = "32586", ["loot_name"] = "Bracers of Nimble Thought", ["prio"] = "Kazlocked, Othercyde, Ularok, Stormish, Piyopiyo, storemount, Penguin, strwbrrynsqk, sygnom",},
{["loot_id"] = "31092", ["loot_name"] = "Gloves of the Forgotten Conqueror", ["prio"] = "Kazlocked, Othercyde, Ularok, Dominoctus, Amrita, storemount, Zanadune, Hemp, sygnom, Cheeps",},
{["loot_id"] = "33497", ["loot_name"] = "Mana Attuned Band", ["prio"] = "Kazlocked, Othercyde, Ularok, storemount, strwbrrynsqk",},
{["loot_id"] = "32527", ["loot_name"] = "Ring of Ancient Knowledge", ["prio"] = "Kazlocked, Othercyde, Ularok, Stormish, Stormish, Piyopiyo, Xoen, Deyat, storemount, Penguin, strwbrrynsqk, sygnom, sygnom",},
{["loot_id"] = "32483", ["loot_name"] = "The Skull of Gul'dan", ["prio"] = "Kazlocked, Othercyde, Ularok, Stormish, Piyopiyo, Xoen, Deyat, Penguin, strwbrrynsqk, sygnom",},
{["loot_id"] = "33829", ["loot_name"] = "Hex Shrunken Head", ["prio"] = "Kazlocked, Othercyde, Ularok, Piyopiyo, Dominoctus, Xoen, Deyat, storemount, Penguin, strwbrrynsqk, sygnom",},
{["loot_id"] = "32331", ["loot_name"] = "Cloak of the Illidari Council", ["prio"] = "Kazlocked, Ularok, Stormish, Piyopiyo, Xoen, Deyat, Penguin, strwbrrynsqk",},
{["loot_id"] = "30910", ["loot_name"] = "Tempest of Chaos", ["prio"] = "Kazlocked, Othercyde, Dominoctus, Xoen, Deyat",},
{["loot_id"] = "30872", ["loot_name"] = "Chronicle of Dark Secrets", ["prio"] = "Kazlocked, Othercyde, Xoen, Deyat",},
{["loot_id"] = "33192", ["loot_name"] = "Carved Witch Doctor's Stick", ["prio"] = "Kazlocked, Othercyde, Ularok, Xoen, Deyat, storemount, sygnom",},
{["loot_id"] = "32235", ["loot_name"] = "Cursed Vision of Sargeras", ["prio"] = "Berggen, Buckkethead, Dtm, Taghan, Huntercrow, DTM, Endai",},
{["loot_id"] = "32591", ["loot_name"] = "Choker of Serrated Blades", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "31103", ["loot_name"] = "Pauldrons of the Forgotten Protector", ["prio"] = "Berggen, Perly, Buckkethead, Dtm, Stormish, Fug2, Penguin, Huntercrow, DTM",},
{["loot_id"] = "5107", ["loot_name"] = "Deckhand's Shirt", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "31091", ["loot_name"] = "Chestguard of the Forgotten Protector", ["prio"] = "Berggen, Perly, Buckkethead, Dtm, Stormish, Fug2, Penguin, Huntercrow, DTM",},
{["loot_id"] = "30032", ["loot_name"] = "Red Belt of Battle", ["prio"] = "Berggen, Cheeps",},
{["loot_id"] = "32341", ["loot_name"] = "Leggings of Divine Retribution", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "32345", ["loot_name"] = "Dreadboots of the Legion", ["prio"] = "Berggen, Buckkethead, Cheeps",},
{["loot_id"] = "30863", ["loot_name"] = "Deadly Cuffs", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "32278", ["loot_name"] = "Grips of Silent Justice", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "32497", ["loot_name"] = "Stormrage Signet Ring", ["prio"] = "Berggen, Buckkethead, Dtm, Taghan, Huntercrow, Endai",},
{["loot_id"] = "32335", ["loot_name"] = "Unstoppable Aggressor's Ring", ["prio"] = "Berggen, Cheeps",},
{["loot_id"] = "32505", ["loot_name"] = "Madness of the Betrayer", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "28830", ["loot_name"] = "Dragonspine Trophy", ["prio"] = "Berggen, Buckkethead, Dtm, Taghan, Huntercrow, DTM, Endai",},
{["loot_id"] = "32323", ["loot_name"] = "Shadowmoon Destroyer's Drape", ["prio"] = "Berggen, Buckkethead, Dtm, Taghan, Huntercrow, DTM, Endai",},
{["loot_id"] = "28439", ["loot_name"] = "Dragonstrike", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "30901", ["loot_name"] = "Boundless Agony", ["prio"] = "Berggen",},
{["loot_id"] = "33474", ["loot_name"] = "Ancient Amani Longbow", ["prio"] = "Berggen, Buckkethead",},
{["loot_id"] = "31095", ["loot_name"] = "Helm of the Forgotten Protector", ["prio"] = "Perly, Stormish, Penguin",},
{["loot_id"] = "32258", ["loot_name"] = "Naturalist's Preserving Cinch", ["prio"] = "Perly",},
{["loot_id"] = "31100", ["loot_name"] = "Leggings of the Forgotten Protector", ["prio"] = "Perly, Dtm, Stormish, Fug2, Penguin, Huntercrow, DTM",},
{["loot_id"] = "33324", ["loot_name"] = "Treads of the Life Path", ["prio"] = "Perly, OrangeSqueez",},
{["loot_id"] = "32577", ["loot_name"] = "Living Earth Bindings", ["prio"] = "Perly",},
{["loot_id"] = "32328", ["loot_name"] = "Botanist's Gloves of Growth", ["prio"] = "Perly, Sliverlight",},
{["loot_id"] = "32528", ["loot_name"] = "Blessed Band of Karabor", ["prio"] = "Perly, Perly, OrangeSqueez, OrangeSqueez, Amrita, Amrita, Zanadune, Zanadune, Sliverlight, Hemp, Hemp",},
{["loot_id"] = "32496", ["loot_name"] = "Memento of Tyrande", ["prio"] = "Perly, OrangeSqueez, Amrita, Zanadune, Sliverlight, Hemp",},
{["loot_id"] = "29376", ["loot_name"] = "Essence of the Martyr", ["prio"] = "Perly, OrangeSqueez, Amrita, Hemp",},
{["loot_id"] = "32524", ["loot_name"] = "Shroud of the Highborne", ["prio"] = "Perly, OrangeSqueez, Amrita, Zanadune, Sliverlight, Hemp",},
{["loot_id"] = "32500", ["loot_name"] = "Crystal Spire of Karabor", ["prio"] = "Perly, OrangeSqueez, Amrita, Zanadune, Sliverlight, Hemp",},
{["loot_id"] = "30882", ["loot_name"] = "Bastion of Light", ["prio"] = "Perly",},
{["loot_id"] = "28523", ["loot_name"] = "Totem of Healing Rains", ["prio"] = "Perly",},
{["loot_id"] = "31096", ["loot_name"] = "Helm of the Forgotten Vanquisher", ["prio"] = "Furballz, Sliverlight, strwbrrynsqk",},
{["loot_id"] = "33923", ["loot_name"] = "Vindicator's Pendant of Triumph", ["prio"] = "Furballz",},
{["loot_id"] = "31102", ["loot_name"] = "Pauldrons of the Forgotten Vanquisher", ["prio"] = "Furballz, Taghan, Piyopiyo, Sliverlight, strwbrrynsqk",},
{["loot_id"] = "31090", ["loot_name"] = "Chestguard of the Forgotten Vanquisher", ["prio"] = "Furballz, Taghan, Piyopiyo, Sliverlight, strwbrrynsqk",},
{["loot_id"] = "30106", ["loot_name"] = "Belt of One-Hundred Deaths", ["prio"] = "Furballz, Buckkethead, Taghan, Endai",},
{["loot_id"] = "31099", ["loot_name"] = "Leggings of the Forgotten Vanquisher", ["prio"] = "Furballz, Taghan, Piyopiyo, Xoen, Deyat",},
{["loot_id"] = "32593", ["loot_name"] = "Treads of the Den Mother", ["prio"] = "Furballz",},
{["loot_id"] = "33881", ["loot_name"] = "Vindicator's Dragonhide Bracers", ["prio"] = "Furballz",},
{["loot_id"] = "31093", ["loot_name"] = "Gloves of the Forgotten Vanquisher", ["prio"] = "Furballz, Taghan, Piyopiyo, strwbrrynsqk",},
{["loot_id"] = "29279", ["loot_name"] = "Violet Signet of the Great Protector", ["prio"] = "Furballz",},
{["loot_id"] = "29278", ["loot_name"] = "Violet Signet", ["prio"] = "Furballz",},
{["loot_id"] = "32658", ["loot_name"] = "Badge of Tenacity", ["prio"] = "Furballz",},
{["loot_id"] = "31858", ["loot_name"] = "Darkmoon Card: Vengeance", ["prio"] = "Furballz, Dominoctus",},
{["loot_id"] = "28660", ["loot_name"] = "Gilded Thorium Cloak", ["prio"] = "Furballz",},
{["loot_id"] = "30883", ["loot_name"] = "Pillar of Ferocity", ["prio"] = "Furballz",},
{["loot_id"] = "30051", ["loot_name"] = "Idol of the Crescent Goddess", ["prio"] = "Furballz",},
{["loot_id"] = "33466", ["loot_name"] = "Loop of Cursed Bones", ["prio"] = "Othercyde, Ularok, storemount, sygnom",},
{["loot_id"] = "31089", ["loot_name"] = "Chestguard of the Forgotten Conqueror", ["prio"] = "Othercyde, OrangeSqueez, Dominoctus, Amrita, storemount, Zanadune, Hemp, sygnom, Cheeps",},
{["loot_id"] = "32256", ["loot_name"] = "Waistwrap of Infinity", ["prio"] = "Othercyde, storemount, sygnom",},
{["loot_id"] = "30916", ["loot_name"] = "Leggings of Channeled Elements", ["prio"] = "Othercyde, storemount, strwbrrynsqk, sygnom",},
{["loot_id"] = "33591", ["loot_name"] = "Shadowcaster's Drape", ["prio"] = "Othercyde",},
{["loot_id"] = "33496", ["loot_name"] = "Signet of Primal Wrath", ["prio"] = "Buckkethead, Dtm, Taghan, Huntercrow, DTM, Endai",},
{["loot_id"] = "32236", ["loot_name"] = "Rising Tide", ["prio"] = "Buckkethead",},
{["loot_id"] = "32260", ["loot_name"] = "Choker of Endless Nightmares", ["prio"] = "Dtm, Taghan, Huntercrow, DTM, Endai",},
{["loot_id"] = "32346", ["loot_name"] = "Boneweave Girdle", ["prio"] = "Dtm, Huntercrow, DTM",},
{["loot_id"] = "32366", ["loot_name"] = "Shadowmaster's Boots", ["prio"] = "Dtm, Taghan, Huntercrow, DTM",},
{["loot_id"] = "32324", ["loot_name"] = "Insidious Bands", ["prio"] = "Dtm, Taghan, Huntercrow, DTM",},
{["loot_id"] = "31094", ["loot_name"] = "Gloves of the Forgotten Protector", ["prio"] = "Dtm, Stormish, Penguin, Huntercrow, DTM",},
{["loot_id"] = "33831", ["loot_name"] = "Berserker's Call", ["prio"] = "Dtm, Taghan, Huntercrow, DTM, Endai, Cheeps",},
{["loot_id"] = "33389", ["loot_name"] = "Dagger of Bad Mojo", ["prio"] = "Dtm, Dtm, Huntercrow, Huntercrow, DTM, DTM",},
{["loot_id"] = "30906", ["loot_name"] = "Bristleblitz Striker", ["prio"] = "Dtm, Huntercrow, DTM",},
{["loot_id"] = "32374", ["loot_name"] = "Zhar'doom, Greatstaff of the Devourer", ["prio"] = "Ularok, Stormish, Piyopiyo, storemount, Penguin, strwbrrynsqk, sygnom",},
{["loot_id"] = "30082", ["loot_name"] = "Talon of Azshara", ["prio"] = "Taghan",},
{["loot_id"] = "32369", ["loot_name"] = "Blade of Savagery", ["prio"] = "Taghan",},
{["loot_id"] = "29949", ["loot_name"] = "Arcanite Steam-Pistol", ["prio"] = "Taghan",},
{["loot_id"] = "32349", ["loot_name"] = "Translucent Spellthread Necklace", ["prio"] = "Stormish",},
{["loot_id"] = "32276", ["loot_name"] = "Flashfire Girdle", ["prio"] = "Stormish, Penguin",},
{["loot_id"] = "29370", ["loot_name"] = "Icon of the Silver Crescent", ["prio"] = "Stormish, storemount",},
{["loot_id"] = "32330", ["loot_name"] = "Totem of Ancestral Guidance", ["prio"] = "Stormish, Penguin",},
{["loot_id"] = "32525", ["loot_name"] = "Cowl of the Illidari High Lord", ["prio"] = "Piyopiyo",},
{["loot_id"] = "32589", ["loot_name"] = "Hellfire-Encased Pendant", ["prio"] = "Piyopiyo",},
{["loot_id"] = "29305", ["loot_name"] = "Band of the Eternal Sage", ["prio"] = "Piyopiyo, Xoen, Deyat, Penguin",},
{["loot_id"] = "29982", ["loot_name"] = "Wand of the Forgotten Star", ["prio"] = "Piyopiyo",},
{["loot_id"] = "32370", ["loot_name"] = "Nadina's Pendant of Purity", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "30897", ["loot_name"] = "Girdle of Hope", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "30862", ["loot_name"] = "Blessed Adamantite Bracers", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "30112", ["loot_name"] = "Glorious Gauntlets of Crestfall", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "32255", ["loot_name"] = "Felstone Bulwark", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "25644", ["loot_name"] = "Blessed Book of Nagrand", ["prio"] = "OrangeSqueez",},
{["loot_id"] = "32521", ["loot_name"] = "Faceplate of the Impenetrable", ["prio"] = "Dominoctus, Fug2",},
{["loot_id"] = "30007", ["loot_name"] = "The Darkener's Grasp", ["prio"] = "Dominoctus",},
{["loot_id"] = "32342", ["loot_name"] = "Girdle of Mighty Resolve", ["prio"] = "Dominoctus",},
{["loot_id"] = "32245", ["loot_name"] = "Tide-Stomper's Greaves", ["prio"] = "Dominoctus",},
{["loot_id"] = "32279", ["loot_name"] = "The Seeker's Wristguards", ["prio"] = "Dominoctus",},
{["loot_id"] = "30028", ["loot_name"] = "Seventh Ring of the Tirisfalen", ["prio"] = "Dominoctus",},
{["loot_id"] = "33499", ["loot_name"] = "Signet of the Last Defender", ["prio"] = "Dominoctus",},
{["loot_id"] = "33593", ["loot_name"] = "Slikk's Cloak of Placation", ["prio"] = "Dominoctus",},
{["loot_id"] = "32375", ["loot_name"] = "Bulwark of Azzinoth", ["prio"] = "Dominoctus, Fug2",},
{["loot_id"] = "32368", ["loot_name"] = "Tome of the Lightbringer", ["prio"] = "Dominoctus",},
{["loot_id"] = "30895", ["loot_name"] = "Angelista's Sash", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "30912", ["loot_name"] = "Leggings of Eternity", ["prio"] = "Amrita, Zanadune, Sliverlight, Hemp",},
{["loot_id"] = "32609", ["loot_name"] = "Boots of the Divine Light", ["prio"] = "Amrita, Zanadune, Sliverlight, Hemp",},
{["loot_id"] = "32584", ["loot_name"] = "Swiftheal Wraps", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "30911", ["loot_name"] = "Scepter of Purification", ["prio"] = "Amrita, Zanadune, Sliverlight, Hemp",},
{["loot_id"] = "32363", ["loot_name"] = "Naaru-Blessed Life Rod", ["prio"] = "Amrita, Zanadune, Hemp",},
{["loot_id"] = "30244", ["loot_name"] = "Helm of the Vanquished Hero", ["prio"] = "Xoen, Deyat",},
{["loot_id"] = "30015", ["loot_name"] = "The Sun King's Talisman", ["prio"] = "Xoen, Deyat",},
{["loot_id"] = "30250", ["loot_name"] = "Pauldrons of the Vanquished Hero", ["prio"] = "Xoen, Deyat",},
{["loot_id"] = "30238", ["loot_name"] = "Chestguard of the Vanquished Hero", ["prio"] = "Xoen, Deyat",},
{["loot_id"] = "30870", ["loot_name"] = "Cuffs of Devastation", ["prio"] = "Xoen, Deyat",},
{["loot_id"] = "30241", ["loot_name"] = "Gloves of the Vanquished Hero", ["prio"] = "Xoen, Deyat",},
{["loot_id"] = "28788", ["loot_name"] = "Tabard of the Protector", ["prio"] = "Xoen",},
{["loot_id"] = "32362", ["loot_name"] = "Pendant of Titans", ["prio"] = "Fug2",},
{["loot_id"] = "32333", ["loot_name"] = "Girdle of Stability", ["prio"] = "Fug2",},
{["loot_id"] = "32268", ["loot_name"] = "Myrmidon's Treads", ["prio"] = "Fug2",},
{["loot_id"] = "32232", ["loot_name"] = "Eternium Shell Bracers", ["prio"] = "Fug2",},
{["loot_id"] = "32280", ["loot_name"] = "Gauntlets of Enforcement", ["prio"] = "Fug2",},
{["loot_id"] = "29297", ["loot_name"] = "Band of the Eternal Defender", ["prio"] = "Fug2",},
{["loot_id"] = "32261", ["loot_name"] = "Band of the Abyssal Lord", ["prio"] = "Fug2",},
{["loot_id"] = "37127", ["loot_name"] = "Brightbrew Charm", ["prio"] = "Fug2",},
{["loot_id"] = "31859", ["loot_name"] = "Darkmoon Card: Madness", ["prio"] = "Fug2",},
{["loot_id"] = "34010", ["loot_name"] = "Pepe's Shroud of Pacification", ["prio"] = "Fug2",},
{["loot_id"] = "32254", ["loot_name"] = "The Brutalizer", ["prio"] = "Fug2",},
{["loot_id"] = "32253", ["loot_name"] = "Legionkiller", ["prio"] = "Fug2",},
{["loot_id"] = "33357", ["loot_name"] = "Footpads of Madness", ["prio"] = "storemount",},
{["loot_id"] = "32590", ["loot_name"] = "Nethervoid Cloak", ["prio"] = "storemount, sygnom",},
{["loot_id"] = "32585", ["loot_name"] = "Swiftheal Mantle", ["prio"] = "Zanadune",},
{["loot_id"] = "38288", ["loot_name"] = "Direbrew Hops", ["prio"] = "Zanadune, Sliverlight",},
{["loot_id"] = "30018", ["loot_name"] = "Lord Sanguinar's Claim", ["prio"] = "Sliverlight",},
{["loot_id"] = "32339", ["loot_name"] = "Belt of Primal Majesty", ["prio"] = "Sliverlight",},
{["loot_id"] = "32582", ["loot_name"] = "Bracers of Renewed Life", ["prio"] = "Sliverlight",},
{["loot_id"] = "29309", ["loot_name"] = "Band of the Eternal Restorer", ["prio"] = "Sliverlight",},
{["loot_id"] = "27886", ["loot_name"] = "Idol of the Emerald Queen", ["prio"] = "Sliverlight",},
{["loot_id"] = "32329", ["loot_name"] = "Cowl of Benevolence", ["prio"] = "Hemp",},
{["loot_id"] = "30038", ["loot_name"] = "Belt of Blasting", ["prio"] = "strwbrrynsqk",},
{["loot_id"] = "32387", ["loot_name"] = "Idol of the Raven Goddess", ["prio"] = "strwbrrynsqk",},
{["loot_id"] = "21870", ["loot_name"] = "Frozen Shadoweave Boots", ["prio"] = "sygnom",},
{["loot_id"] = "29301", ["loot_name"] = "Band of the Eternal Champion", ["prio"] = "DTM",},
{["loot_id"] = "32581", ["loot_name"] = "Swiftstrike Shoulders", ["prio"] = "Endai",},
{["loot_id"] = "4335", ["loot_name"] = "Rich Purple Silk Shirt", ["prio"] = "Endai",},
{["loot_id"] = "30905", ["loot_name"] = "Midnight Chestguard", ["prio"] = "Endai",},
{["loot_id"] = "30900", ["loot_name"] = "Bow-Stitched Leggings", ["prio"] = "Endai",},
{["loot_id"] = "32510", ["loot_name"] = "Softstep Boots of Tracking", ["prio"] = "Endai",},
{["loot_id"] = "32574", ["loot_name"] = "Bindings of Lightning Reflexes", ["prio"] = "Endai",},
{["loot_id"] = "32234", ["loot_name"] = "Fists of Mukoa", ["prio"] = "Endai",},
{["loot_id"] = "32262", ["loot_name"] = "Syphon of the Nathrezim", ["prio"] = "Endai, Endai",},
{["loot_id"] = "33507", ["loot_name"] = "Stonebreaker's Totem", ["prio"] = "Endai",},
{["loot_id"] = "32373", ["loot_name"] = "Helm of the Illidari Shatterer", ["prio"] = "Cheeps",},
{["loot_id"] = "33297", ["loot_name"] = "The Savage's Choker", ["prio"] = "Cheeps",},
{["loot_id"] = "30866", ["loot_name"] = "Blood-Stained Pauldrons", ["prio"] = "Cheeps",},
{["loot_id"] = "3427", ["loot_name"] = "Stylish Black Shirt", ["prio"] = "Cheeps",},
{["loot_id"] = "30903", ["loot_name"] = "Legguards of Endless Rage", ["prio"] = "Cheeps",},
{["loot_id"] = "30861", ["loot_name"] = "Furious Shackles", ["prio"] = "Cheeps",},
{["loot_id"] = "30834", ["loot_name"] = "Shapeshifter's Signet", ["prio"] = "Cheeps",},
{["loot_id"] = "29383", ["loot_name"] = "Bloodlust Brooch", ["prio"] = "Cheeps",},
{["loot_id"] = "33590", ["loot_name"] = "Cloak of Fiends", ["prio"] = "Cheeps",},
{["loot_id"] = "32332", ["loot_name"] = "Torch of the Damned", ["prio"] = "Cheeps",},
{["loot_id"] = "27484", ["loot_name"] = "Libram of Avengement", ["prio"] = "Cheeps",},
{["loot_id"] = "25549", ["loot_name"] = "Blood Knight Tabard", ["prio"] = "Cheeps",},
}
